const D=(name,category,display,body,background,foreground,accent,grid,motion,depth='flat',radius='medium')=>({name,category,typography:{display,body},color:{background,foreground,accent},grid,motion,depth,radius});

export const DESIGN_DIRECTIONS=[
D('Luxury Editorial','luxury','Cormorant Garamond','Inter','#f7f4ef','#171717','#c7a86b','asymmetric editorial','restrained cinematic','layered'),
D('Modern Minimal','minimal','DM Sans','DM Sans','#ffffff','#111111','#111111','strict grid','quiet micro-interactions','flat','small'),
D('Futuristic 3D','futuristic','Space Grotesk','Inter','#070b12','#eef7ff','#8cf0ff','spatial','cinematic scroll + camera','3d'),
D('Modern Corporate','corporate','Manrope','Inter','#f7f9fc','#142033','#2457d6','12-column','purposeful','flat'),
D('Premium Corporate','corporate','Manrope','Inter','#f4f1ea','#18202b','#b48a5a','editorial grid','restrained reveal','layered'),
D('Swiss Grid','corporate','Helvetica Neue','Inter','#f5f5f2','#111111','#d32f2f','Swiss modular','minimal','flat','small'),
D('Executive','corporate','Manrope','Inter','#eef1f5','#142033','#536dfe','structured','subtle','layered'),
D('Financial','corporate','IBM Plex Sans','Inter','#f6f8fa','#10233d','#0b6e4f','data grid','subtle','flat','small'),
D('Consulting','corporate','Manrope','Inter','#ffffff','#182230','#2447a8','content grid','quiet','flat','small'),
D('Enterprise','corporate','Inter','Inter','#f4f6f8','#17202a','#1463ff','dense modular','purposeful','flat','small'),
D('SaaS Premium','saas','Space Grotesk','Inter','#f8fafc','#101828','#635bff','product grid','micro-interactions','glass'),
D('Clean B2B','corporate','Inter','Inter','#ffffff','#1d2939','#175cd3','12-column','quiet','flat','small'),
D('Creative Studio','creative','Syne','Inter','#f2eee8','#191716','#ff5c35','asymmetric','expressive','layered'),
D('Art Direction','creative','Neue Montreal','Inter','#111111','#f4f1ea','#d7ff3f','experimental','art-directed','layered'),
D('Experimental Editorial','creative','Playfair Display','Inter','#f1eadf','#201b18','#b33a2b','magazine','cinematic','layered'),
D('Typography First','creative','Space Grotesk','Inter','#ffffff','#101010','#101010','type-led','kinetic type','flat','small'),
D('Magazine','editorial','Playfair Display','Source Sans 3','#f4efe8','#201c19','#a23d2b','editorial columns','page-like transitions','flat'),
D('Brutalist','creative','Arial Black','Arial','#f2f2f0','#0a0a0a','#ff3b30','raw asymmetric','hard cuts','flat','small'),
D('Neo Brutalist','creative','Space Grotesk','Inter','#f4f0e8','#111111','#ff6b00','modular blocks','snappy','flat','small'),
D('Luxury Fashion','fashion','Bodoni Moda','Inter','#f6f3ee','#151515','#b9975b','runway editorial','slow cinematic','layered'),
D('High Fashion','fashion','Didot','Helvetica Neue','#f8f7f4','#141414','#8f7a52','asymmetric','editorial reveals','flat'),
D('Automotive Luxury','automotive','Montserrat','Inter','#0b0d10','#f4f6f8','#c9a227','cinematic split','camera-like motion','3d'),
D('Dark Premium','luxury','DM Sans','Inter','#0b0b0c','#f5f5f5','#d6b36a','cinematic','slow parallax','layered'),
D('Light Premium','luxury','Manrope','Inter','#fbfaf7','#151515','#c7a86b','airy editorial','soft reveal','layered'),
D('White / Ice Premium','luxury','Inter','Inter','#f4f8fb','#14202a','#9ed8ff','spacious','glass micro-motion','glass'),
D('Champagne Gold','luxury','Cormorant Garamond','Inter','#f7f0e6','#211d19','#c8a46a','luxury editorial','slow reveal','layered'),
D('Glassmorphism','futuristic','Inter','Inter','#0d1320','#edf6ff','#75e6ff','floating cards','blur transitions','glass','large'),
D('Holographic','futuristic','Space Grotesk','Inter','#090b14','#f7f7ff','#c9a7ff','spatial','iridescent','3d','large'),
D('Cyber','futuristic','Space Mono','Inter','#05070b','#d8fff4','#00ff9d','terminal grid','glitch-lite','layered','small'),
D('AI / Technology','futuristic','Space Grotesk','Inter','#07111f','#eaf4ff','#4cc9f0','data spatial','signal motion','3d'),
D('Spatial UI','futuristic','Inter','Inter','#080a0f','#f5f7fb','#7c8cff','depth grid','camera transitions','3d','large'),
D('Fashion Storefront','commerce','DM Sans','Inter','#faf9f6','#151515','#111111','commerce grid','product hover','flat','small'),
D('Luxury Product','commerce','Manrope','Inter','#f5f2ec','#181818','#b99a62','product editorial','slow product motion','layered'),
D('Minimal Product','commerce','Inter','Inter','#ffffff','#111111','#111111','clean commerce','micro-interactions','flat','small'),
D('Product Launch','commerce','Space Grotesk','Inter','#090b10','#f5f7ff','#8cf0ff','story panels','scroll narrative','3d'),
D('Marketplace','commerce','Inter','Inter','#f7f8fa','#17202a','#2563eb','dense catalog','quick feedback','flat','small'),
D('Architectural Editorial','architecture','Space Grotesk','Inter','#e9e7e2','#20211f','#b48a5a','architectural','slow cinematic','layered'),
D('Luxury Property','realestate','Manrope','Inter','#f6f2ea','#191714','#b99052','property editorial','cinematic parallax','layered'),
D('Developer Corporate','realestate','Manrope','Inter','#f4f6f8','#17202a','#2457d6','structured property','subtle','flat'),
D('Interactive Floorplan','architecture','Space Grotesk','Inter','#f3f0e8','#1b1b19','#a8875a','diagram grid','guided hotspots','3d'),
D('Cinematic Property','realestate','Montserrat','Inter','#08090b','#f5f5f5','#d2b06b','full bleed','cinematic','3d'),
D('Interior Design Portfolio','architecture','DM Sans','Inter','#f5f1eb','#20201e','#9b7653','gallery editorial','image transitions','layered'),
D('Luxury Hotel','hospitality','Cormorant Garamond','Inter','#f5f0e7','#211d19','#c4a46a','resort editorial','slow cinematic','layered'),
D('Boutique Hotel','hospitality','DM Sans','Inter','#f2eee7','#25221e','#9a6a45','asymmetric','soft reveal','layered'),
D('Resort','hospitality','Manrope','Inter','#eef6f4','#15322d','#1c8c78','immersive','parallax','layered'),
D('Fine Dining','hospitality','Bodoni Moda','Inter','#101010','#f4eee2','#d0a75b','editorial','slow reveal','layered'),
D('Restaurant Editorial','hospitality','Playfair Display','Source Sans 3','#f6efe6','#251f1a','#a84b2a','magazine','scroll reveal','flat'),
D('Church Modern','community','Manrope','Inter','#f5f8fb','#172033','#4169e1','community grid','warm reveal','flat'),
D('Education','community','DM Sans','Inter','#f7fafc','#1d2939','#2563eb','modular','friendly micro-motion','flat','medium'),
D('Healthcare','community','Inter','Inter','#f8fbfc','#16323a','#008c95','clinical grid','calm','flat','small'),
D('Personal Brand','personal','Manrope','Inter','#f7f5f2','#171717','#7657d9','editorial personal','subtle','layered'),
D('Portfolio','personal','Space Grotesk','Inter','#111111','#f4f4f4','#ffffff','project grid','scroll narrative','flat','small'),
D('Agency','creative','Manrope','Inter','#f5f3ef','#171717','#ff5b2e','case-study grid','purposeful','layered')
];

export const DESIGN_DIRECTION_NAMES=DESIGN_DIRECTIONS.map(d=>d.name);
export function getDesignDirections(){return DESIGN_DIRECTIONS.map(d=>({...d,typography:{...d.typography},color:{...d.color}}));}
export function resolveDesignDirection(input=''){const q=String(input||'').toLowerCase();return DESIGN_DIRECTIONS.find(d=>d.name.toLowerCase()===q||d.name.toLowerCase().includes(q)||q.includes(d.name.toLowerCase()))||DESIGN_DIRECTIONS[0];}
export function rankDesignDirections(brief={}){const text=JSON.stringify(brief).toLowerCase();const score=d=>{let n=0;if(text.includes(d.category))n+=4;if(text.includes(d.name.toLowerCase()))n+=12;if(/luxury|premium|fashion|hotel|automotive/.test(text)&&d.category==='luxury')n+=8;if(/3d|webgl|interactive|ai|technology|cyber/.test(text)&&d.depth==='3d')n+=8;if(/restaurant|hotel|hospitality/.test(text)&&d.category==='hospitality')n+=7;if(/property|real estate|architecture|interior/.test(text)&&['architecture','realestate'].includes(d.category))n+=7;if(/saas|software|startup|technology/.test(text)&&['saas','futuristic','corporate'].includes(d.category))n+=5;if(/church|education|healthcare|community/.test(text)&&d.category==='community')n+=7;return n};return[...DESIGN_DIRECTIONS].sort((a,b)=>score(b)-score(a)).map((d,i)=>({...d,matchScore:score(d),rank:i+1}));}
export function buildArtDirectionMatrix(brief={},count=5){return rankDesignDirections(brief).slice(0,Math.max(1,Math.min(10,count))).map(d=>({name:d.name,category:d.category,visualSystem:d,reason:`${d.name} aligns with the brief's industry, positioning, audience and requested visual language.`}));}
