const D=(name,category,display,body,background,foreground,accent,grid,motion,depth='flat',radius='medium',keywords=[])=>({name,category,typography:{display,body},color:{background,foreground,accent},grid,motion,depth,radius,keywords});

export const DESIGN_DIRECTIONS=[
D('Luxury Editorial','luxury','Cormorant Garamond','Inter','#f7f4ef','#171717','#c7a86b','asymmetric editorial','restrained cinematic','layered'),
D('Modern Minimal','minimal','DM Sans','DM Sans','#ffffff','#111111','#111111','strict grid','quiet micro-interactions','flat','small'),
D('Futuristic 3D','futuristic','Space Grotesk','Inter','#070b12','#eef7ff','#8cf0ff','spatial','cinematic scroll + camera','3d'),
D('Modern Corporate','corporate','Manrope','Inter','#f7f9fc','#142033','#2457d6','12-column','purposeful','flat'),
D('Premium Corporate','corporate','Manrope','Inter','#f4f1ea','#18202b','#b48a5a','editorial grid','restrained reveal','layered'),
D('Swiss Grid','corporate','Helvetica Neue','Inter','#f5f5f2','#111111','#d32f2f','Swiss modular','minimal','flat','small'),
D('Executive','corporate','Manrope','Inter','#eef1f5','#142033','#536dfe','structured','subtle','layered'),
D('Financial','corporate','IBM Plex Sans','Inter','#f6f8fa','#10233d','#0b6e4f','data grid','subtle','flat','small'),
D('Consulting','corporate','Manrope','Inter','#ffffff','#182230','#2447a8','content grid','quiet','flat','small'),
D('Enterprise','corporate','Inter','Inter','#f4f6f8','#17202a','#1463ff','dense modular','purposeful','flat','small'),
D('SaaS Premium','saas','Space Grotesk','Inter','#f8fafc','#101828','#635bff','product grid','micro-interactions','glass'),
D('Clean B2B','corporate','Inter','Inter','#ffffff','#1d2939','#175cd3','12-column','quiet','flat','small'),
D('Creative Studio','creative','Syne','Inter','#f2eee8','#191716','#ff5c35','asymmetric','expressive','layered'),
D('Art Direction','creative','Neue Montreal','Inter','#111111','#f4f1ea','#d7ff3f','experimental','art-directed','layered'),
D('Experimental Editorial','creative','Playfair Display','Inter','#f1eadf','#201b18','#b33a2b','magazine','cinematic','layered'),
D('Typography First','creative','Space Grotesk','Inter','#ffffff','#101010','#101010','type-led','kinetic type','flat','small'),
D('Magazine','editorial','Playfair Display','Source Sans 3','#f4efe8','#201c19','#a23d2b','editorial columns','page-like transitions','flat'),
D('Brutalist','creative','Arial Black','Arial','#f2f2f0','#0a0a0a','#ff3b30','raw asymmetric','hard cuts','flat','small'),
D('Neo Brutalist','creative','Space Grotesk','Inter','#f4f0e8','#111111','#ff6b00','modular blocks','snappy','flat','small'),
D('Luxury Fashion','fashion','Bodoni Moda','Inter','#f6f3ee','#151515','#b9975b','runway editorial','slow cinematic','layered'),
D('High Fashion','fashion','Didot','Helvetica Neue','#f8f7f4','#141414','#8f7a52','asymmetric','editorial reveals','flat'),
D('Automotive Luxury','automotive','Montserrat','Inter','#0b0d10','#f4f6f8','#c9a227','cinematic split','camera-like motion','3d'),
D('Dark Premium','luxury','DM Sans','Inter','#0b0b0c','#f5f5f5','#d6b36a','cinematic','slow parallax','layered'),
D('Light Premium','luxury','Manrope','Inter','#fbfaf7','#151515','#c7a86b','airy editorial','soft reveal','layered'),
D('White / Ice Premium','luxury','Inter','Inter','#f4f8fb','#14202a','#9ed8ff','spacious','glass micro-motion','glass'),
D('Champagne Gold','luxury','Cormorant Garamond','Inter','#f7f0e6','#211d19','#c8a46a','luxury editorial','slow reveal','layered'),
D('Glassmorphism','futuristic','Inter','Inter','#0d1320','#edf6ff','#75e6ff','floating cards','blur transitions','glass','large'),
D('Holographic','futuristic','Space Grotesk','Inter','#090b14','#f7f7ff','#c9a7ff','spatial','iridescent','3d','large'),
D('Cyber','futuristic','Space Mono','Inter','#05070b','#d8fff4','#00ff9d','terminal grid','glitch-lite','layered','small'),
D('AI / Technology','futuristic','Space Grotesk','Inter','#07111f','#eaf4ff','#4cc9f0','data spatial','signal motion','3d'),
D('Spatial UI','futuristic','Inter','Inter','#080a0f','#f5f7fb','#7c8cff','depth grid','camera transitions','3d','large'),
D('Fashion Storefront','commerce','DM Sans','Inter','#faf9f6','#151515','#111111','commerce grid','product hover','flat','small'),
D('Luxury Product','commerce','Manrope','Inter','#f5f2ec','#181818','#b99a62','product editorial','slow product motion','layered'),
D('Minimal Product','commerce','Inter','Inter','#ffffff','#111111','#111111','clean commerce','micro-interactions','flat','small'),
D('Product Launch','commerce','Space Grotesk','Inter','#090b10','#f5f7ff','#8cf0ff','story panels','scroll narrative','3d'),
D('Marketplace','commerce','Inter','Inter','#f7f8fa','#17202a','#2563eb','dense catalog','quick feedback','flat','small'),
D('Architectural Editorial','architecture','Space Grotesk','Inter','#e9e7e2','#20211f','#b48a5a','architectural','slow cinematic','layered'),
D('Luxury Property','realestate','Manrope','Inter','#f6f2ea','#191714','#b99052','property editorial','cinematic parallax','layered'),
D('Developer Corporate','realestate','Manrope','Inter','#f4f6f8','#17202a','#2457d6','structured property','subtle','flat'),
D('Interactive Floorplan','architecture','Space Grotesk','Inter','#f3f0e8','#1b1b19','#a8875a','diagram grid','guided hotspots','3d'),
D('Cinematic Property','realestate','Montserrat','Inter','#08090b','#f5f5f5','#d2b06b','full bleed','cinematic','3d'),
D('Interior Design Portfolio','architecture','DM Sans','Inter','#f5f1eb','#20201e','#9b7653','gallery editorial','image transitions','layered'),
D('Luxury Hotel','hospitality','Cormorant Garamond','Inter','#f5f0e7','#211d19','#c4a46a','resort editorial','slow cinematic','layered'),
D('Boutique Hotel','hospitality','DM Sans','Inter','#f2eee7','#25221e','#9a6a45','asymmetric','soft reveal','layered'),
D('Resort','hospitality','Manrope','Inter','#eef6f4','#15322d','#1c8c78','immersive','parallax','layered'),
D('Fine Dining','hospitality','Bodoni Moda','Inter','#101010','#f4eee2','#d0a75b','editorial','slow reveal','layered'),
D('Restaurant Editorial','hospitality','Playfair Display','Source Sans 3','#f6efe6','#251f1a','#a84b2a','magazine','scroll reveal','flat'),
D('Church Modern','community','Manrope','Inter','#f5f8fb','#172033','#4169e1','community grid','warm reveal','flat'),
D('Education','community','DM Sans','Inter','#f7fafc','#1d2939','#2563eb','modular','friendly micro-motion','flat','medium'),
D('Healthcare','community','Inter','Inter','#f8fbfc','#16323a','#008c95','clinical grid','calm','flat','small'),
D('Personal Brand','personal','Manrope','Inter','#f7f5f2','#171717','#7657d9','editorial personal','subtle','layered'),
D('Portfolio','personal','Space Grotesk','Inter','#111111','#f4f4f4','#ffffff','project grid','scroll narrative','flat','small'),
D('Agency','creative','Manrope','Inter','#f5f3ef','#171717','#ff5b2e','case-study grid','purposeful','layered'),
D('Luxury Editorial Dark','luxury','Bodoni Moda','Inter','#151311','#f7f1e7','#d2ad6d','art-directed spread','slow cinematic','layered'),
D('Monochrome Gallery','editorial','Inter','Inter','#f1f1ef','#171717','#777777','gallery grid','fade + scale','flat','small'),
D('Neo Glass Light','futuristic','Manrope','Inter','#eef4f8','#17212b','#7bc7ff','floating modular','soft depth','glass','large'),
D('Chrome Studio','creative','Space Grotesk','Inter','#0d0e10','#f5f7fa','#c7cbd1','metallic grid','reflective motion','3d','medium'),
D('Editorial Commerce','commerce','Playfair Display','Inter','#faf6ef','#211c17','#b7834f','story commerce','product reveal','layered'),
D('Luxury Automotive Light','automotive','Montserrat','Inter','#f3f5f7','#151a20','#b58b4d','cinematic split','precision motion','3d'),
D('Coastal Hospitality','hospitality','Manrope','Inter','#f3f8f5','#17352f','#2f8f83','airy resort','slow parallax','layered'),
D('Modern Ministry','community','Manrope','Inter','#f7f9fc','#15243a','#315fbd','modular community','warm cinematic','flat'),
D('Data Editorial','corporate','IBM Plex Sans','Inter','#f5f7fa','#111827','#1d7a63','editorial data','chart reveal','flat'),
D('Neo Swiss','corporate','Helvetica Neue','Inter','#f8f8f6','#141414','#0057ff','strict modular','hard reveal','flat','small'),
D('Soft Luxury','luxury','DM Sans','Inter','#faf7f2','#28221d','#d1aa7a','soft asymmetric','gentle reveal','layered'),
D('Kinetic Type','creative','Space Grotesk','Inter','#0f1115','#f4f6f8','#ff5a5f','type grid','kinetic typography','flat','small'),
D('Digital Museum','editorial','Cormorant Garamond','Inter','#ebe7df','#1c1a17','#9b6f45','curated rooms','gallery transitions','layered'),
D('Tech Noir','futuristic','Space Mono','Inter','#050505','#f0f0ed','#ff4d6d','dark data grid','signal + parallax','3d','small'),
D('Solar Minimal','minimal','DM Sans','Inter','#fbfaf4','#172019','#7a9b4a','open grid','quiet natural','flat','small'),
D('Luxury Real Estate Light','realestate','Manrope','Inter','#f8f5ef','#1b1b1a','#ad8755','gallery property','cinematic reveal','layered'),
D('Hospitality Editorial','hospitality','Playfair Display','Inter','#f6f0e7','#2a211b','#b36b43','editorial hospitality','slow reveal','layered'),
D('Product Gallery','commerce','Inter','Inter','#f7f7f5','#161616','#303030','gallery commerce','image choreography','flat','small'),
D('Future Commerce','commerce','Space Grotesk','Inter','#080b12','#eef5ff','#8cf0ff','spatial commerce','scroll + 3d','3d','large'),
D('Quiet Luxury','luxury','Canela','Inter','#fbf8f3','#211f1c','#bda06a','quiet editorial','soft cinematic','layered','medium'),
D('Editorial Luxe Light','luxury','Cormorant Garamond','Inter','#fffdf8','#191817','#b89a6a','asymmetric editorial','slow reveal','layered'),
D('Pearl Minimal','minimal','Manrope','Inter','#f8f7f4','#202225','#c6c2ba','strict grid','whisper motion','flat','small'),
D('Nordic Calm','minimal','DM Sans','Inter','#f4f6f3','#24302b','#8a9b8f','open grid','calm micro-motion','flat','medium'),
D('Organic Modern','minimal','Sora','Inter','#f3f0e8','#25251f','#7b8f58','organic grid','fluid reveal','layered','large'),
D('Editorial Ink','editorial','Bodoni Moda','Source Sans 3','#eeeae2','#171514','#8d2f27','editorial columns','ink reveal','flat'),
D('Newspaper Modern','editorial','Libre Baskerville','Inter','#f5f1e8','#1b1b1b','#a33b2e','dense editorial','page transitions','flat','small'),
D('Gallery White','editorial','Neue Montreal','Inter','#ffffff','#161616','#222222','gallery grid','fade + scale','flat','small'),
D('Luxury Beauty','fashion','Bodoni Moda','Inter','#fbf5f2','#241d1d','#c98f9b','editorial beauty','silk reveal','layered','large'),
D('Runway Black','fashion','Didot','Inter','#0c0c0d','#f7f2ea','#d5b37a','runway editorial','catwalk motion','layered'),
D('Street Fashion','fashion','Space Grotesk','Inter','#e9e7e3','#141414','#ff5a36','poster grid','snappy cuts','flat','small'),
D('Performance Automotive','automotive','Montserrat','Inter','#11151a','#eef2f5','#d8a84e','cinematic split','accelerated camera','3d'),
D('Electric Mobility','automotive','Sora','Inter','#eef5f7','#11232a','#28a7a0','spatial','fluid camera','3d','large'),
D('PropTech Spatial','realestate','Space Grotesk','Inter','#eef2f3','#18232a','#4c8da6','spatial property','camera walkthrough','3d','large'),
D('Developer Luxury','realestate','Manrope','Inter','#f5f1e9','#1d1c1a','#b18a57','property editorial','cinematic reveal','layered'),
D('Architecture Monolith','architecture','Neue Montreal','Inter','#e5e2db','#1b1c1a','#7b7368','monolithic grid','architectural scroll','layered'),
D('Architecture Blueprint','architecture','IBM Plex Sans','Inter','#e8edf0','#17222b','#3d78a8','diagram grid','technical reveal','flat','small'),
D('Resort Sunset','hospitality','Cormorant Garamond','Inter','#f5eee6','#2a211b','#c97852','full bleed','slow cinematic','layered','large'),
D('Urban Boutique','hospitality','DM Sans','Inter','#ebe8e1','#252321','#b06a3c','asymmetric','street-level reveal','layered'),
D('Wellness Retreat','hospitality','Manrope','Inter','#eef4ef','#1e3429','#6f9d78','airy resort','breathing motion','layered','large'),
D('Chef Portfolio','hospitality','Playfair Display','Inter','#faf5ed','#241d18','#a65a32','project grid','dish reveal','flat'),
D('Fintech Trust','corporate','Inter','Inter','#f4f8f7','#12252a','#16836f','12-column','precision micro-motion','flat','small'),
D('Legal Authority','corporate','Libre Baskerville','Inter','#f5f4f0','#20252b','#294b67','structured','restrained reveal','flat'),
D('Healthcare Premium','community','Manrope','Inter','#f4f8f9','#17333b','#0d8b91','clinical grid','calm reveal','glass','medium'),
D('Nonprofit Impact','community','DM Sans','Inter','#f5f8f4','#213228','#3f8b5b','community grid','human reveal','flat'),
D('Youth Ministry','community','Sora','Inter','#f4f7fb','#17243b','#5578e8','modular','energetic warm motion','flat','large'),
D('Learning Lab','community','Space Grotesk','Inter','#f7f8f5','#172018','#76a94b','content grid','playful micro-motion','flat','medium'),
D('AI Research Lab','futuristic','IBM Plex Mono','Inter','#070b0d','#e8f5f1','#56d6a0','data grid','signal motion','3d','small'),
D('Quantum Interface','futuristic','Space Grotesk','Inter','#060914','#eef2ff','#8f9cff','spatial','orbital camera','3d','large'),
D('Digital Product Lab','futuristic','Sora','Inter','#0c1017','#f0f5ff','#6ba6ff','floating modular','fluid interface','glass','large'),
D('Creator Economy','commerce','Manrope','Inter','#f7f4ee','#211d1a','#8d61d8','content commerce','card choreography','layered'),
D('Luxury Marketplace','commerce','Cormorant Garamond','Inter','#f8f5ef','#1e1b18','#bd9b64','commerce editorial','premium product reveal','layered'),
D('Direct-to-Consumer','commerce','Sora','Inter','#f6f8fa','#17212a','#ff6b35','product grid','conversion motion','flat','medium'),
D('Subscription SaaS','saas','Inter','Inter','#f8fafc','#101828','#7f56d9','product grid','progressive reveal','glass'),
D('Developer SaaS','saas','JetBrains Mono','Inter','#0b0e12','#e7edf4','#5eead4','data grid','terminal motion','layered','small'),
D('AI SaaS Premium','saas','Space Grotesk','Inter','#f7f8fc','#161b2a','#6d5dfc','spatial','intelligent motion','glass','large'),
D('Luxury Travel','hospitality','Cormorant Garamond','Inter','#f4eee5','#241e19','#b28a57','immersive','cinematic journey','layered','large'),
D('Travel Editorial','editorial','Playfair Display','Inter','#f5efe5','#25201b','#b55f3e','editorial columns','chapter transitions','flat'),
D('Cultural Institution','editorial','Neue Montreal','Inter','#efeee9','#1e201f','#8a6b45','gallery editorial','curated reveal','layered'),
D('Sports Performance','creative','Sora','Inter','#0e1217','#f2f6fa','#f04d3d','dynamic grid','kinetic','3d','small'),
D('Fitness Premium','community','Manrope','Inter','#f1f4f2','#18231f','#65a66f','modular','energetic reveal','flat','medium'),
D('Beauty Clinic','community','DM Sans','Inter','#fbf7f6','#2a2022','#c77d8c','airy editorial','soft reveal','glass','large'),
D('Old Money','luxury','Cormorant Garamond','Inter','#f4efe5','#24201a','#8f6f43','quiet editorial','measured reveal','layered','medium',['heritage','estate','classic','old money','private club']),
D('Contemporary Luxury','luxury','Canela','Inter','#f9f7f2','#1c1b19','#a88b63','spacious editorial','silk transitions','layered','large',['modern luxury','premium lifestyle','high-end','refined']),
D('Jewelry Atelier','fashion','Bodoni Moda','Inter','#fbfaf8','#211f1d','#bfa26a','gallery editorial','jewel reveal','3d','large',['jewelry','diamonds','atelier','fine jewelry','watches']),
D('Luxury Cosmetics','fashion','Cormorant Garamond','Inter','#f9f3f1','#2b2022','#c68f9b','beauty grid','silk reveal','layered','large',['cosmetics','makeup','beauty','premium beauty']),
D('Private Aviation','luxury','Manrope','Inter','#eef1f4','#17202a','#b4935a','cinematic split','flight-path motion','3d','large',['private jet','aviation','charter','executive travel']),
D('Yacht Club','luxury','Cormorant Garamond','Inter','#edf4f5','#173139','#b48b56','full bleed','oceanic parallax','layered','large',['yacht','marine','nautical','superyacht']),
D('Fashion Lookbook','fashion','Didot','Inter','#f5f2ee','#181818','#a38a6a','runway editorial','page choreography','flat','small',['lookbook','collection','runway','fashion editorial']),
D('Streetwear Commerce','fashion','Space Grotesk','Inter','#151515','#f5f5f3','#ff5a1f','poster grid','snappy product motion','flat','small',['streetwear','sneakers','urban fashion','youth fashion']),
D('Motorsport','automotive','Sora','Inter','#090c10','#f4f7fa','#e64032','dynamic grid','race camera','3d','small',['motorsport','racing','formula','performance car']),
D('Premium Dealer','automotive','Montserrat','Inter','#f5f6f7','#151a20','#b58b4d','cinematic split','precision reveal','layered','medium',['car dealer','dealership','premium automotive','showroom']),
D('Automotive Technology','automotive','Space Grotesk','Inter','#0a1015','#eaf5f7','#45c7d1','data spatial','telemetry motion','3d','large',['automotive technology','connected car','autonomous','vehicle tech']),
D('Residential Living','realestate','Manrope','Inter','#f6f2eb','#24211d','#a98760','property editorial','soft walkthrough','layered','large',['residential','homes','living','housing']),
D('Commercial Property','realestate','Inter','Inter','#eef2f4','#17232b','#3c6f8f','12-column','precision reveal','flat','small',['commercial real estate','office','retail property','commercial']),
D('Property Investment','realestate','IBM Plex Sans','Inter','#f4f7f6','#15252a','#18705f','data grid','metric reveal','flat','small',['property investment','real estate investment','investors','portfolio']),
D('Spatial Walkthrough','architecture','Space Grotesk','Inter','#080d11','#edf5f8','#7ed8e8','spatial','camera walkthrough','3d','large',['walkthrough','virtual tour','spatial','architecture visualization']),
D('Wellness Luxury','hospitality','Manrope','Inter','#eef4ef','#1d3328','#7b9e80','airy resort','breathing motion','layered','large',['wellness','spa','retreat','mindfulness']),
D('Cultural Tourism','hospitality','Cormorant Garamond','Inter','#f2ede4','#2a241e','#a77449','immersive','journey chapters','layered','large',['cultural tourism','heritage travel','destination','travel']),
D('DTC Story Commerce','commerce','Sora','Inter','#f7f5ef','#1d1c1a','#ef6b42','story commerce','scroll conversion','layered','medium',['direct to consumer','dtc','brand commerce','conversion']),
D('Subscription Commerce','commerce','DM Sans','Inter','#f7f9fb','#17202a','#6b5bd2','product grid','progressive reveal','glass','medium',['subscription','membership','recurring','consumer service']),
D('Creator Commerce','commerce','Sora','Inter','#f6f3fa','#201a2a','#8d61d8','content commerce','creator choreography','layered','large',['creator commerce','influencer','creator','digital products']),
D('AI SaaS Research','saas','Space Grotesk','Inter','#f5f7fb','#111827','#635bff','data spatial','intelligent signal','glass','large',['ai saas','machine learning','ai product','research platform']),
D('Cloud Platform','saas','Inter','Inter','#f5f8fb','#14212e','#1976d2','12-column','system reveal','flat','small',['cloud','cloud platform','infrastructure','devops']),
D('Cybersecurity Command','futuristic','IBM Plex Mono','Inter','#05090d','#e9f6f2','#31d18b','terminal grid','threat signal','3d','small',['cybersecurity','security','soc','threat intelligence']),
D('Data Intelligence','futuristic','IBM Plex Sans','Inter','#071017','#eaf2f7','#45b8d8','data grid','data flow','3d','medium',['data','analytics','business intelligence','dashboard']),
D('Robotics Lab','futuristic','Sora','Inter','#0a0d12','#eef3f7','#ff8a3d','spatial','mechanical motion','3d','large',['robotics','robots','automation','industrial tech']),
D('Fintech Wealth','corporate','Manrope','Inter','#f3f7f5','#15231f','#0d8b68','data grid','precision reveal','flat','small',['wealth','investment','fintech','banking']),
D('Insurance Trust','corporate','Inter','Inter','#f4f7fa','#172637','#2b6cb0','structured','confidence reveal','flat','small',['insurance','risk','claims','financial protection']),
D('Professional Services','corporate','Manrope','Inter','#f7f8fa','#1c2733','#476b8f','content grid','quiet reveal','flat','medium',['professional services','advisory','accounting','law firm']),
D('Digital Ministry','community','Sora','Inter','#f5f8fc','#17243a','#5578e8','community grid','warm cinematic','layered','large',['church','ministry','sermons','worship']),
D('Community Foundation','community','DM Sans','Inter','#f4f8f4','#1d3024','#4e9364','community grid','human reveal','flat','medium',['ngo','foundation','community','social impact']),
D('Motion First Studio','creative','Sora','Inter','#0b0d12','#f3f6fa','#ff5b5b','experimental','kinetic transitions','3d','small',['motion design','animation','creative studio','motion first'])
];

export const DESIGN_DIRECTION_NAMES=DESIGN_DIRECTIONS.map(d=>d.name);
export function getDesignDirections(){return DESIGN_DIRECTIONS.map(d=>({...d,typography:{...d.typography},color:{...d.color}}));}
export function resolveDesignDirection(input=''){const q=String(input||'').trim().toLowerCase();const exact=DESIGN_DIRECTIONS.find(d=>d.name.toLowerCase()===q);if(exact)return exact;return DESIGN_DIRECTIONS.find(d=>d.name.toLowerCase().includes(q)||q.includes(d.name.toLowerCase()))||DESIGN_DIRECTIONS[0];}
export function rankDesignDirections(brief={}){const text=JSON.stringify(brief).toLowerCase();const tokens=text.split(/[^a-z0-9]+/).filter(Boolean);const score=d=>{let n=0;const haystack=[d.name,d.category,...(d.keywords||[]),d.grid,d.motion,d.depth].join(' ').toLowerCase();if(text.includes(d.name.toLowerCase()))n+=18;if(text.includes(d.category))n+=4;for(const keyword of d.keywords||[]){const k=String(keyword).toLowerCase();if(text.includes(k))n+=5;}for(const token of tokens){if(token.length>3&&haystack.includes(token))n+=1;}if(/3d|webgl|interactive|spatial|viewer/.test(text)&&d.depth==='3d')n+=8;if(/luxury|premium|high-end|fashion|jewelry|beauty/.test(text)&&['luxury','fashion'].includes(d.category))n+=6;if(/restaurant|hotel|resort|hospitality|travel|wellness/.test(text)&&d.category==='hospitality')n+=7;if(/property|real estate|architecture|interior|walkthrough/.test(text)&&['architecture','realestate'].includes(d.category))n+=7;if(/saas|software|startup|technology|cloud|ai/.test(text)&&['saas','futuristic','corporate'].includes(d.category))n+=5;if(/church|education|healthcare|ngo|community|ministry/.test(text)&&d.category==='community')n+=7;if(/commerce|ecommerce|shop|product|subscription|marketplace/.test(text)&&d.category==='commerce')n+=6;if(/automotive|car|vehicle|motorsport|ev/.test(text)&&d.category==='automotive')n+=8;return n};return[...DESIGN_DIRECTIONS].sort((a,b)=>score(b)-score(a)).map((d,i)=>({...d,matchScore:score(d),rank:i+1}));}
export function buildArtDirectionMatrix(brief={},count=5){return rankDesignDirections(brief).slice(0,Math.max(1,Math.min(10,count))).map(d=>({name:d.name,category:d.category,visualSystem:d,reason:`${d.name} aligns with the brief's industry, positioning, audience and requested visual language.`}));}
