export const WEBSITE_ENGINE_SLICE2_VERSION = '2.0.0';
export const THREE_VERSION = '0.180.0';
export const THREE_MODULE_URL = `https://cdn.jsdelivr.net/npm/three@${THREE_VERSION}/build/three.module.js`;
export const GLTF_LOADER_URL = `https://cdn.jsdelivr.net/npm/three@${THREE_VERSION}/examples/jsm/loaders/GLTFLoader.js`;

export const WEBSITE_SLICE2_VIEWPORTS = Object.freeze({
  mobile: { width: 390, height: 844 },
  tablet: { width: 768, height: 1024 },
  desktop: { width: 1440, height: 900 },
  largeDesktop: { width: 1920, height: 1080 },
});

export const WEBSITE_SLICE2_DELIVERY_PATHS = Object.freeze([
  'source/', 'assets/', 'components/', 'pages/', 'styles/', 'design-tokens/',
  'configuration/', 'SEO/', 'documentation/', 'tests/', 'deployment/', 'README',
]);

const clean = (value, fallback = '') => String(value ?? fallback).trim();
const escapeHtml = (value) => clean(value).replace(/[&<>"']/g, (char) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
}[char]));

export function createWebsiteSlice2Spec(input = {}) {
  const title = clean(input.title, 'Premium Website');
  const description = clean(input.description, 'Production-grade responsive website generated by the Website Engine.');
  const reducedMotion = input.reducedMotion === true;
  return {
    version: WEBSITE_ENGINE_SLICE2_VERSION,
    title,
    description,
    theme: clean(input.theme, 'luxury-editorial'),
    components: [
      'site-header', 'hero', 'feature-grid', 'media-gallery', 'proof',
      'testimonials', 'cta', 'site-footer', 'three-d-hero',
    ],
    threeD: {
      enabled: input.threeD?.enabled !== false,
      canvasId: clean(input.threeD?.canvasId, 'website-3d-hero'),
      modelUrl: clean(input.threeD?.modelUrl),
      fallbackImage: clean(input.threeD?.fallbackImage),
      interaction: input.threeD?.interaction !== false,
      lighting: 'directional-plus-ambient',
      camera: 'hero-perspective',
      loader: 'GLTFLoader',
      engine: 'Three.js',
      version: THREE_VERSION,
    },
    motion: {
      enabled: input.motion?.enabled !== false,
      reducedMotion,
      reveal: 'intersection-observer',
      easing: 'cubic-bezier(.22,1,.36,1)',
      durationMs: 700,
      fallback: reducedMotion ? 'static' : 'crossfade',
    },
    qa: {
      viewports: WEBSITE_SLICE2_VIEWPORTS,
      checks: ['layout', 'overflow', 'contrast', 'hierarchy', 'media', 'responsive', 'motion', 'threeD'],
      maxRepairAttempts: 3,
    },
    performance: {
      lcpMs: 2500,
      cls: 0.1,
      jsKb: 350,
      lazyMedia: true,
    },
    accessibility: {
      standard: 'WCAG 2.2 AA',
      contrastRatio: 4.5,
      keyboardFocus: true,
      semanticLandmarks: true,
      labelsRequired: true,
      reducedMotion: true,
    },
    security: {
      externalScriptAllowlist: ['cdn.jsdelivr.net'],
      noInlineSecrets: true,
      modelProtocol: ['https:', 'data:'],
    },
    delivery: {
      paths: WEBSITE_SLICE2_DELIVERY_PATHS,
      preview: true,
      sourceManifest: true,
      checksum: true,
    },
  };
}

export function validateWebsiteSlice2Spec(spec = {}) {
  const failures = [];
  if (spec.version !== WEBSITE_ENGINE_SLICE2_VERSION) failures.push('version');
  if (!clean(spec.title)) failures.push('title');
  if (!Array.isArray(spec.components) || spec.components.length < 6) failures.push('components');
  if (spec.threeD?.engine !== 'Three.js') failures.push('three-engine');
  if (spec.threeD?.loader !== 'GLTFLoader') failures.push('gltf-loader');
  if (!spec.motion?.reveal) failures.push('motion');
  if (spec.motion?.reducedMotion !== true && spec.motion?.fallback !== 'crossfade') failures.push('motion-fallback');
  if (!Array.isArray(spec.qa?.checks) || !spec.qa.checks.includes('threeD')) failures.push('qa-threeD');
  if (spec.qa?.maxRepairAttempts !== 3) failures.push('repair-bound');
  if (spec.performance?.lcpMs > 2500 || spec.performance?.cls > 0.1) failures.push('performance-budget');
  if (spec.accessibility?.standard !== 'WCAG 2.2 AA') failures.push('accessibility-standard');
  if (!spec.accessibility?.reducedMotion) failures.push('accessibility-motion');
  for (const requiredPath of WEBSITE_SLICE2_DELIVERY_PATHS) {
    if (!spec.delivery?.paths?.includes(requiredPath)) failures.push(`delivery:${requiredPath}`);
  }
  return { passed: failures.length === 0, failures };
}

export function createWebsiteDeliveryManifest(spec = {}) {
  const qa = validateWebsiteSlice2Spec(spec);
  return {
    engine: 'professional-website-slice2',
    version: WEBSITE_ENGINE_SLICE2_VERSION,
    status: qa.passed ? 'READY_FOR_EXPORT' : 'BLOCKED',
    folders: [...WEBSITE_SLICE2_DELIVERY_PATHS],
    runtime: { three: THREE_VERSION, gltf: true, reducedMotion: spec.motion?.reducedMotion === true },
    qaGate: qa,
  };
}

export function buildWebsiteRepairPlan(report = {}, maxAttempts = 3) {
  const attempts = Math.max(0, Math.min(3, Number(maxAttempts) || 3));
  const failures = Array.isArray(report.failures) ? report.failures : [];
  const fixes = failures.slice(0, attempts).map((failure, index) => ({
    attempt: index + 1,
    issue: String(failure),
    action: failure.includes('overflow') ? 'reduce-layout-overflow'
      : failure.includes('contrast') ? 'raise-text-contrast'
        : failure.includes('three') ? 'activate-3d-fallback-and-recheck'
          : 'regenerate-targeted-component',
  }));
  return { maxAttempts: attempts, bounded: true, status: fixes.length ? 'REPAIR_REQUIRED' : 'PASS', fixes };
}

export function evaluateWebsiteRuntimeQa(snapshot = {}) {
  const failures = [];
  if (snapshot.overflow === true) failures.push('overflow');
  if (snapshot.missingAlt > 0) failures.push('accessibility:missing-alt');
  if (snapshot.missingLabels > 0) failures.push('accessibility:missing-label');
  if (snapshot.contrastPass === false) failures.push('contrast');
  if (snapshot.motionPass === false) failures.push('motion');
  if (snapshot.threeDPass === false) failures.push('threeD');
  if (Number(snapshot.lcpMs) > 2500) failures.push('performance:lcp');
  if (Number(snapshot.cls) > 0.1) failures.push('performance:cls');
  return { passed: failures.length === 0, failures, repair: buildWebsiteRepairPlan({ failures }, 3) };
}

export function renderWebsiteSlice2Html(spec = createWebsiteSlice2Spec()) {
  const qa = validateWebsiteSlice2Spec(spec);
  if (!qa.passed) throw new Error(`Website Slice 2 spec blocked: ${qa.failures.join(', ')}`);
  const modelUrl = spec.threeD.modelUrl ? JSON.stringify(spec.threeD.modelUrl) : 'null';
  const reducedMotion = spec.motion.reducedMotion ? 'true' : 'false';
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="${escapeHtml(spec.description)}">
<title>${escapeHtml(spec.title)}</title>
<style>
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;--bg:#090a0d;--fg:#f7f7f4;--muted:#a8abb3;--accent:#d8b36a;--radius:24px}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 70% 10%,#242018 0,#090a0d 42%);color:var(--fg);line-height:1.55}a{color:inherit}button,a{outline-offset:4px}button:focus-visible,a:focus-visible{outline:2px solid var(--accent)}
.skip{position:absolute;left:12px;top:12px;transform:translateY(-150%);background:#fff;color:#000;padding:10px 14px;border-radius:10px;z-index:10}.skip:focus{transform:none}
header,main,footer{width:min(1180px,calc(100% - 32px));margin:auto}header{display:flex;align-items:center;justify-content:space-between;padding:22px 0}nav{display:flex;gap:18px}main{display:grid;gap:32px}.hero{min-height:68vh;display:grid;grid-template-columns:1.1fr .9fr;gap:30px;align-items:center}.hero h1{font-size:clamp(2.8rem,7vw,6.8rem);line-height:.95;margin:0 0 20px}.hero p{font-size:1.12rem;color:var(--muted);max-width:62ch}.panel{border:1px solid #34363d;border-radius:var(--radius);background:#111319cc;padding:28px;backdrop-filter:blur(18px)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.reveal{opacity:0;transform:translateY(24px);transition:opacity .7s var(--ease),transform .7s var(--ease)}.reveal.is-visible{opacity:1;transform:none}#${escapeHtml(spec.threeD.canvasId)}{display:block;width:100%;height:100%;min-height:520px;border-radius:var(--radius);background:linear-gradient(145deg,#17181d,#07080a);touch-action:none}.fallback{display:none}.three-disabled .fallback{display:block}.three-disabled canvas{display:none}footer{padding:60px 0;color:var(--muted)}
@media(max-width:900px){.hero{grid-template-columns:1fr}.grid{grid-template-columns:1fr 1fr}#${escapeHtml(spec.threeD.canvasId)}{min-height:420px}}@media(max-width:600px){header{align-items:flex-start}nav{gap:10px;font-size:.9rem}.grid{grid-template-columns:1fr}.hero{min-height:auto;padding:45px 0}.hero h1{font-size:clamp(2.7rem,14vw,4.5rem)}#${escapeHtml(spec.threeD.canvasId)}{min-height:330px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.reveal{opacity:1;transform:none;transition:none}}
</style>
</head>
<body data-website-engine="slice2" data-website-engine-version="${WEBSITE_ENGINE_SLICE2_VERSION}">
<a class="skip" href="#main">Skip to content</a>
<header aria-label="Primary"><strong>${escapeHtml(spec.title)}</strong><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#proof">Proof</a><a href="#contact">Contact</a></nav></header>
<main id="main">
<section class="hero reveal" aria-labelledby="hero-title"><div><p>Website Engine • Slice 2</p><h1 id="hero-title">${escapeHtml(spec.title)}</h1><p>${escapeHtml(spec.description)}</p><p><a href="#contact">Explore the experience →</a></p></div><div class="panel"><canvas id="${escapeHtml(spec.threeD.canvasId)}" aria-label="Interactive 3D product visualization"></canvas><img class="fallback" alt="3D visualization fallback" src="${escapeHtml(spec.threeD.fallbackImage)}"></div></section>
<section id="work" class="reveal" aria-labelledby="work-title"><div class="panel"><h2 id="work-title">Premium components</h2><div class="grid">${spec.components.slice(0,6).map((name) => `<article><h3>${escapeHtml(name.replaceAll('-', ' '))}</h3><p>Reusable responsive component with motion-safe behavior and semantic structure.</p></article>`).join('')}</div></div></section>
<section id="proof" class="reveal" aria-labelledby="proof-title"><div class="panel"><h2 id="proof-title">Built for production</h2><p>Responsive rendering, 3D runtime, reduced-motion support, accessibility gates, performance budgets and bounded repair are part of the generated contract.</p></div></section>
<section id="contact" class="reveal" aria-labelledby="contact-title"><div class="panel"><h2 id="contact-title">Ready for review</h2><form><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" required><button type="submit">Request review</button></form></div></section>
</main><footer><small>Website Engine Slice 2 • ${WEBSITE_ENGINE_SLICE2_VERSION}</small></footer>
<script type="module">
const A6={version:${JSON.stringify(WEBSITE_ENGINE_SLICE2_VERSION)},threeVersion:${JSON.stringify(THREE_VERSION)},modelUrl:${modelUrl},reducedMotion:${reducedMotion}};window.__WEBSITE_ENGINE_A6__=A6;window.__A6_READY__=false;
const canvas=document.getElementById(${JSON.stringify(spec.threeD.canvasId)});const body=document.body;
const reveal=()=>{if(${reducedMotion}||window.matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.reveal').forEach(e=>e.classList.add('is-visible'));return;}const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('is-visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));};reveal();
try{const THREE=await import(${JSON.stringify(THREE_MODULE_URL)});const {GLTFLoader}=await import(${JSON.stringify(GLTF_LOADER_URL)});const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.setSize(canvas.clientWidth||640,canvas.clientHeight||520,false);const scene=new THREE.Scene();scene.background=new THREE.Color(0x090a0d);const camera=new THREE.PerspectiveCamera(45,(canvas.clientWidth||640)/(canvas.clientHeight||520),.1,100);camera.position.set(0,0,5);scene.add(new THREE.AmbientLight(0xffffff,1.4));const light=new THREE.DirectionalLight(0xffffff,2.2);light.position.set(3,4,5);scene.add(light);let target=null;if(A6.modelUrl){await new Promise((resolve,reject)=>new GLTFLoader().load(A6.modelUrl,g=>{target=g.scene;scene.add(target);resolve();},undefined,reject));}else{const mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(1.45,2),new THREE.MeshPhysicalMaterial({color:0xd8b36a,metalness:.72,roughness:.22,clearcoat:.65}));scene.add(mesh);target=mesh;}const resize=()=>{const w=canvas.clientWidth||640,h=canvas.clientHeight||520;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);};addEventListener('resize',resize);resize();let pointer=0;canvas.addEventListener('pointermove',e=>{if(A6.reducedMotion)return;pointer=(e.clientX/window.innerWidth-.5)*.5;});const frame=()=>{if(!A6.reducedMotion&&target){target.rotation.y+=.003;target.rotation.x+=(pointer-target.rotation.x)*.02;}renderer.render(scene,camera);requestAnimationFrame(frame)};body.dataset.threeReady='true';window.__A6_THREE__=THREE;window.__A6_GLTF_LOADER__=GLTFLoader;window.__A6_READY__=true;frame();}catch(error){body.classList.add('three-disabled');body.dataset.threeError=String(error?.message||error);window.__A6_READY__=true;window.__A6_RUNTIME_ERROR__=String(error?.message||error);}
</script>
</body></html>`;
}
