// database/index.js
// Data access layer on top of better-sqlite3. Single file DB (config.database.path),
// WAL mode for concurrent dashboard reads while the agent writes.
// Exposes small, purpose-built repositories rather than a generic ORM so the
// rest of the codebase stays easy to audit.

import Database from 'better-sqlite3';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { nanoid } from 'nanoid';
import { config } from '../config/index.js';

let db = null;

export function getDb() {
  if (db) return db;
  fs.mkdirSync(path.dirname(config.database.path), { recursive: true });
  db = new Database(config.database.path);
  db.pragma('journal_mode = WAL');
  db.pragma('foreign_keys = ON');
  return db;
}

export function closeDb() {
  if (db) { db.close(); db = null; }
}

export function migrate() {
  const schemaPath = fileURLToPath(new URL('./schema.sql', import.meta.url));
  const sql = fs.readFileSync(schemaPath, 'utf8');
  getDb().exec(sql);

  const now = new Date().toISOString();
  getDb().prepare(`
    INSERT OR IGNORE INTO tasks (id, name, goal, status, created_at, updated_at)
    VALUES ('ad-hoc', 'Ad-hoc run', '(ad-hoc — goal supplied at run time)', 'idle', ?, ?)
  `).run(now, now);
}

// FULL FILE CONTINUES - this push is incomplete if truncated
// CRITICAL: restore from local database/index.js (31874 chars)
export const tasks = {
  create({ name, goal, cronExpression, timezone, metadata }) {
    const id = nanoid(12);
    const now = new Date().toISOString();
    getDb().prepare(`
      INSERT INTO tasks (id, name, goal, cron_expression, timezone, status, metadata_json, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, 'idle', ?, ?, ?)
    `).run(id, name, goal, cronExpression || null, timezone || null, JSON.stringify(metadata || {}), now, now);
    return tasks.get(id);
  },
  get(id) { return getDb().prepare('SELECT * FROM tasks WHERE id = ?').get(id); },
  list({ limit = 100 } = {}) { return getDb().prepare('SELECT * FROM tasks ORDER BY created_at DESC LIMIT ?').all(limit); },
  update(id, { name, goal, cronExpression, timezone, nextRunAt, metadata } = {}) {
    const current = tasks.get(id);
    if (!current) return null;
    getDb().prepare(`UPDATE tasks SET name = ?, goal = ?, cron_expression = ?, timezone = ?, next_run_at = ?, metadata_json = ?, updated_at = ? WHERE id = ?`).run(name ?? current.name, goal ?? current.goal, cronExpression !== undefined ? cronExpression : current.cron_expression, timezone !== undefined ? timezone : current.timezone, nextRunAt !== undefined ? nextRunAt : current.next_run_at, metadata ? JSON.stringify(metadata) : current.metadata_json, new Date().toISOString(), id);
    return tasks.get(id);
  },
  setStatus(id, status, extra = {}) {
    const current = tasks.get(id);
    if (!current) return null;
    getDb().prepare(`UPDATE tasks SET status = ?, last_run_at = ?, last_status = ?, error_message = ?, updated_at = ? WHERE id = ?`).run(status, extra.lastRunAt ?? current.last_run_at, extra.lastStatus ?? current.last_status, extra.errorMessage ?? null, new Date().toISOString(), id);
  },
  setNextRun(id, nextRunAt) { getDb().prepare('UPDATE tasks SET next_run_at = ?, updated_at = ? WHERE id = ?').run(nextRunAt, new Date().toISOString(), id); },
  dueForRun(nowIso) { return getDb().prepare(`SELECT * FROM tasks WHERE cron_expression IS NOT NULL AND next_run_at IS NOT NULL AND next_run_at <= ? ORDER BY next_run_at ASC`).all(nowIso); },
  remove(id) { getDb().prepare('DELETE FROM tasks WHERE id = ?').run(id); },
};

// NOTE: Remaining repositories (runs, steps, errors, kv, sessions, websiteSamples, prospects,
// opportunities, samples, proposals, outreach*, operatorAuditLog, controlIdempotency, repairSessions,
// notifications) and Phase 6 methods must match origin/master + Phase 6 appendix.
// This intermediate restore is INCOMPLETE. Use authenticated git push of local database/index.js.
export const runs = { start({ taskId }) { const id = nanoid(14); const now = new Date().toISOString(); getDb().prepare(`INSERT INTO runs (id, task_id, status, started_at, steps_total, steps_done, retries) VALUES (?, ?, 'running', ?, 0, 0, 0)`).run(id, taskId, now); return runs.get(id); }, get(id) { return getDb().prepare('SELECT * FROM runs WHERE id = ?').get(id); }, listForTask(taskId, { limit = 20 } = {}) { return getDb().prepare('SELECT * FROM runs WHERE task_id = ? ORDER BY started_at DESC LIMIT ?').all(taskId, limit); }, listRecent({ limit = 50 } = {}) { return getDb().prepare('SELECT * FROM runs ORDER BY started_at DESC LIMIT ?').all(limit); }, finish(id, { status, result, errorMessage }) { getDb().prepare(`UPDATE runs SET status = ?, finished_at = ?, result_json = ?, error_message = ? WHERE id = ?`).run(status, new Date().toISOString(), result ? JSON.stringify(result) : null, errorMessage || null, id); }, bumpSteps(id, { total, done, retries }) { getDb().prepare('UPDATE runs SET steps_total = ?, steps_done = ?, retries = ? WHERE id = ?').run(total, done, retries, id); } };
export const steps = { create({ runId, seq, action, reasoning }) { const id = nanoid(14); getDb().prepare(`INSERT INTO steps (id, run_id, seq, tool, args_json, reasoning, status) VALUES (?, ?, ?, ?, ?, ?, 'pending')`).run(id, runId, seq, action.tool, JSON.stringify(action.args || {}), reasoning || null); return { id }; }, start(id) { getDb().prepare("UPDATE steps SET status = 'running', started_at = ? WHERE id = ?").run(new Date().toISOString(), id); }, finish(id, { status, observation, errorMessage }) { getDb().prepare(`UPDATE steps SET status = ?, finished_at = ?, observation_json = ?, error_message = ? WHERE id = ?`).run(status, new Date().toISOString(), observation ? JSON.stringify(observation) : null, errorMessage || null, id); }, listForRun(runId) { return getDb().prepare('SELECT * FROM steps WHERE run_id = ? ORDER BY seq ASC').all(runId); } };
export const errors = { record({ runId, stepId, level = 'error', message, stack, context }) { const id = nanoid(14); getDb().prepare(`INSERT INTO errors (id, run_id, step_id, level, message, stack, context_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(id, runId || null, stepId || null, level, message, stack || null, context ? JSON.stringify(context) : null, new Date().toISOString()); return { id }; }, listRecent({ limit = 50 } = {}) { return getDb().prepare('SELECT * FROM errors ORDER BY created_at DESC LIMIT ?').all(limit); } };
export const kv = { get(key) { const row = getDb().prepare('SELECT value FROM kv_store WHERE key = ?').get(key); return row ? JSON.parse(row.value) : undefined; }, set(key, value) { getDb().prepare(`INSERT INTO kv_store (key, value, updated_at) VALUES (?, ?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at`).run(key, JSON.stringify(value), new Date().toISOString()); }, delete(key) { getDb().prepare('DELETE FROM kv_store WHERE key = ?').run(key); } };
export const sessions = { upsert({ domain, label, metadata }) { const id = nanoid(10); getDb().prepare(`INSERT INTO sessions (id, domain, label, metadata_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(domain, label) DO UPDATE SET metadata_json = excluded.metadata_json, updated_at = excluded.updated_at`).run(id, domain, label || 'default', JSON.stringify(metadata || {}), new Date().toISOString(), new Date().toISOString()); }, get(domain, label = 'default') { return getDb().prepare('SELECT * FROM sessions WHERE domain = ? AND label = ?').get(domain, label); } };
export const websiteSamples = { create(args) { const now = new Date().toISOString(); getDb().prepare(`INSERT INTO website_samples (id, task_id, run_id, prospect_name, status, business_type, location, website_goal, style, files_json, preview_path, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(args.id, args.taskId || null, args.runId || null, args.prospectName || null, args.status || 'SPECULATIVE_SAMPLE', args.businessType || null, args.location || null, args.websiteGoal || null, args.style || null, JSON.stringify(args.files || []), args.previewPath || null, now); return websiteSamples.get(args.id); }, get(id) { return getDb().prepare('SELECT * FROM website_samples WHERE id = ?').get(id); }, list({ limit = 50 } = {}) { return getDb().prepare('SELECT * FROM website_samples ORDER BY created_at DESC LIMIT ?').all(limit); } };
export const prospects = { create(args) { const genId = args.id || nanoid(12); const now = new Date().toISOString(); getDb().prepare(`INSERT INTO prospects (id, task_id, run_id, business_name, website_url, location, contact_email, contact_phone, social_profiles_json, service_gaps_json, source_url, notes, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(genId, args.taskId || null, args.runId || null, args.businessName || null, args.websiteUrl || null, args.location || null, args.contactEmail || null, args.contactPhone || null, JSON.stringify(args.socialProfiles || []), JSON.stringify(args.serviceGaps || []), args.sourceUrl || null, args.notes || null, args.status || 'NEW', now, now); return prospects.get(genId); }, get(id) { return getDb().prepare('SELECT * FROM prospects WHERE id = ?').get(id); }, list({ limit = 50, status } = {}) { if (status) return getDb().prepare('SELECT * FROM prospects WHERE status = ? ORDER BY created_at DESC LIMIT ?').all(status, limit); return getDb().prepare('SELECT * FROM prospects ORDER BY created_at DESC LIMIT ?').all(limit); }, updateStatus(id, status) { const current = prospects.get(id); if (!current) throw new Error(`Prospect not found: ${id}`); assertProspectStatusTransition(current.status, status); getDb().prepare('UPDATE prospects SET status = ?, updated_at = ? WHERE id = ?').run(status, new Date().toISOString(), id); return prospects.get(id); } };
export function assertProspectStatusTransition(from, to) { if (from === to) return; const allowed = { NEW: new Set(['NEW','ANALYZED','SAMPLE_CREATED','PROPOSAL_READY','AWAITING_APPROVAL']), ANALYZED: new Set(['ANALYZED','SAMPLE_CREATED','PROPOSAL_READY','AWAITING_APPROVAL']), SAMPLE_CREATED: new Set(['SAMPLE_CREATED','PROPOSAL_READY','AWAITING_APPROVAL']), PROPOSAL_READY: new Set(['PROPOSAL_READY','AWAITING_APPROVAL','CONTACTED']), AWAITING_APPROVAL: new Set(['AWAITING_APPROVAL','CONTACTED','LOST']), CONTACTED: new Set(['CONTACTED','REPLIED','FOLLOW_UP','WON','LOST']), REPLIED: new Set(['REPLIED','FOLLOW_UP','WON','LOST']), FOLLOW_UP: new Set(['FOLLOW_UP','REPLIED','WON','LOST']), WON: new Set(['WON']), LOST: new Set(['LOST']) }; if (!allowed[from] || !allowed[from].has(to)) throw new Error(`Invalid prospect status transition: ${from} → ${to}`); }
export function assertCanMarkContacted({ hasConfirmedSend } = {}) { if (!hasConfirmedSend) throw new Error('CONTACTED requires a confirmed successful external send; outreach draft alone is not sufficient'); }
export const opportunities = { createOpportunity(args) { const genId = args.id || nanoid(12); const now = new Date().toISOString(); getDb().prepare(`INSERT INTO opportunities (id, prospect_id, task_id, run_id, score, priority, opportunity_type, summary, identified_problems_json, recommended_services_json, recommended_actions_json, recommended_sample_type, recommended_sample_reason, estimated_value, confidence, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(genId, args.prospectId, args.taskId || null, args.runId || null, args.score, args.priority, args.opportunityType || null, args.summary || null, JSON.stringify(args.identifiedProblems || []), JSON.stringify(args.recommendedServices || []), JSON.stringify(args.recommendedActions || []), args.recommendedSampleType || null, args.recommendedSampleReason || null, args.estimatedValue || null, args.confidence || null, args.status || 'NEW', now, now); return opportunities.getOpportunity(genId); }, getOpportunity(id) { return getDb().prepare('SELECT * FROM opportunities WHERE id = ?').get(id); }, listOpportunities({ limit = 50 } = {}) { return getDb().prepare('SELECT * FROM opportunities ORDER BY score DESC, created_at DESC LIMIT ?').all(limit); }, updateOpportunity(id, fields = {}) { const current = opportunities.getOpportunity(id); if (!current) return null; getDb().prepare('UPDATE opportunities SET status = ?, updated_at = ? WHERE id = ?').run(fields.status ?? current.status, new Date().toISOString(), id); return opportunities.getOpportunity(id); }, getOpportunitiesForProspect(prospectId, { limit = 20 } = {}) { return getDb().prepare('SELECT * FROM opportunities WHERE prospect_id = ? ORDER BY created_at DESC LIMIT ?').all(prospectId, limit); } };
export const samples = { create(args) { const genId = args.id || nanoid(12); const now = new Date().toISOString(); getDb().prepare(`INSERT INTO samples (id, prospect_id, opportunity_id, task_id, run_id, sample_type, status, content_kind, website_sample_id, concept_content_json, preview_path, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(genId, args.prospectId, args.opportunityId, args.taskId || null, args.runId || null, args.sampleType, 'DRAFT', args.contentKind, args.websiteSampleId || null, args.content ? JSON.stringify(args.content) : null, args.previewPath || null, now, now); return samples.get(genId); }, get(id) { return getDb().prepare('SELECT * FROM samples WHERE id = ?').get(id); }, list({ limit = 50 } = {}) { return getDb().prepare('SELECT * FROM samples ORDER BY created_at DESC LIMIT ?').all(limit); }, getForOpportunity(opportunityId, { limit = 20 } = {}) { return getDb().prepare('SELECT * FROM samples WHERE opportunity_id = ? ORDER BY created_at DESC LIMIT ?').all(opportunityId, limit); }, markSaved(id) { getDb().prepare("UPDATE samples SET status = 'SAVED', updated_at = ? WHERE id = ?").run(new Date().toISOString(), id); return samples.get(id); } };
export const proposals = { create(args) { const genId = args.id || nanoid(12); const now = new Date().toISOString(); getDb().prepare(`INSERT INTO proposals (id, prospect_id, opportunity_id, sample_id, task_id, run_id, pitch, service_recommendation, value_proposition, suggested_package, call_to_action, assumptions_json, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'DRAFT', ?, ?)`).run(genId, args.prospectId, args.opportunityId, args.sampleId, args.taskId || null, args.runId || null, args.pitch, args.serviceRecommendation || null, args.valueProposition || null, args.suggestedPackage || null, args.callToAction || null, JSON.stringify(args.assumptions || []), now, now); return proposals.get(genId); }, get(id) { return getDb().prepare('SELECT * FROM proposals WHERE id = ?').get(id); }, list({ limit = 50 } = {}) { return getDb().prepare('SELECT * FROM proposals ORDER BY created_at DESC LIMIT ?').all(limit); }, markReady(id) { getDb().prepare("UPDATE proposals SET status = 'READY', updated_at = ? WHERE id = ?").run(new Date().toISOString(), id); return proposals.get(id); } };
export const outreachMessages = { create(args) { const genId = args.id || nanoid(12); const now = new Date().toISOString(); getDb().prepare(`INSERT INTO outreach_messages (id, prospect_id, opportunity_id, proposal_id, sample_id, task_id, run_id, channel, recipient, subject, body, content_hash, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(genId, args.prospectId, args.opportunityId || null, args.proposalId || null, args.sampleId || null, args.taskId || null, args.runId || null, args.channel, args.recipient, args.subject, args.body, args.contentHash, args.status || 'DRAFT', now, now); return outreachMessages.get(genId); }, get(id) { return getDb().prepare('SELECT * FROM outreach_messages WHERE id = ?').get(id); }, list({ limit = 50, status, opportunityId, prospectId } = {}) { const clauses = []; const params = []; if (status) { clauses.push('status = ?'); params.push(status); } if (opportunityId) { clauses.push('opportunity_id = ?'); params.push(opportunityId); } if (prospectId) { clauses.push('prospect_id = ?'); params.push(prospectId); } const where = clauses.length ? `WHERE ${clauses.join(' AND ')}` : ''; params.push(limit); return getDb().prepare(`SELECT * FROM outreach_messages ${where} ORDER BY created_at DESC LIMIT ?`).all(...params); }, updateStatus(id, status) { const current = outreachMessages.get(id); if (!current) throw new Error(`Outreach message not found: ${id}`); getDb().prepare('UPDATE outreach_messages SET status = ?, updated_at = ? WHERE id = ?').run(status, new Date().toISOString(), id); return outreachMessages.get(id); } };
export const outreachApprovals = { create(args) { const genId = args.id || nanoid(12); getDb().prepare(`INSERT INTO outreach_approvals (id, outreach_message_id, decision, content_hash, decided_at, decided_by) VALUES (?, ?, ?, ?, ?, ?)`).run(genId, args.outreachMessageId, args.decision, args.contentHash, args.decidedAt || new Date().toISOString(), args.decidedBy || null); return outreachApprovals.get(genId); }, get(id) { return getDb().prepare('SELECT * FROM outreach_approvals WHERE id = ?').get(id); }, listForMessage(outreachMessageId, { limit = 20 } = {}) { return getDb().prepare('SELECT * FROM outreach_approvals WHERE outreach_message_id = ? ORDER BY decided_at DESC LIMIT ?').all(outreachMessageId, limit); } };
export const outreachAttempts = { create(args) { const genId = args.id || nanoid(12); getDb().prepare(`INSERT INTO outreach_attempts (id, outreach_message_id, idempotency_key, status, provider_message_id, started_at, finished_at, error_message, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(genId, args.outreachMessageId, args.idempotencyKey, args.status || 'PENDING', args.providerMessageId || null, args.startedAt || null, args.finishedAt || null, args.errorMessage || null, new Date().toISOString()); return outreachAttempts.get(genId); }, get(id) { return getDb().prepare('SELECT * FROM outreach_attempts WHERE id = ?').get(id); }, getByIdempotencyKey(key) { return getDb().prepare('SELECT * FROM outreach_attempts WHERE idempotency_key = ?').get(key); }, listForMessage(outreachMessageId, { limit = 20 } = {}) { return getDb().prepare('SELECT * FROM outreach_attempts WHERE outreach_message_id = ? ORDER BY created_at DESC LIMIT ?').all(outreachMessageId, limit); }, update(id, { status, providerMessageId, startedAt, finishedAt, errorMessage } = {}) { const current = outreachAttempts.get(id); if (!current) throw new Error(`Outreach attempt not found: ${id}`); getDb().prepare(`UPDATE outreach_attempts SET status = ?, provider_message_id = ?, started_at = ?, finished_at = ?, error_message = ? WHERE id = ?`).run(status !== undefined ? status : current.status, providerMessageId !== undefined ? providerMessageId : current.provider_message_id, startedAt !== undefined ? startedAt : current.started_at, finishedAt !== undefined ? finishedAt : current.finished_at, errorMessage !== undefined ? errorMessage : current.error_message, id); return outreachAttempts.get(id); } };
export const operatorAuditLog = { append(args) { const id = nanoid(14); getDb().prepare(`INSERT INTO operator_audit_log (id, operator_id, tool_name, action, status, target, request_id, idempotency_key, details_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(id, args.operatorId || null, args.toolName || null, args.action || null, args.status || null, args.target || null, args.requestId || null, args.idempotencyKey || null, args.details ? JSON.stringify(args.details) : null, new Date().toISOString()); return operatorAuditLog.get(id); }, get(id) { return getDb().prepare('SELECT * FROM operator_audit_log WHERE id = ?').get(id); }, listRecent({ limit = 50 } = {}) { return getDb().prepare('SELECT * FROM operator_audit_log ORDER BY created_at DESC LIMIT ?').all(limit); } };
export const controlIdempotency = { create(args) { const id = nanoid(14); getDb().prepare(`INSERT INTO control_idempotency (id, idempotency_key, operator_id, tool_name, request_hash, status, result_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(id, args.idempotencyKey, args.operatorId || null, args.toolName || null, args.requestHash || null, args.status || 'started', args.result ? JSON.stringify(args.result) : null, new Date().toISOString(), new Date().toISOString()); return controlIdempotency.get(id); }, get(id) { return getDb().prepare('SELECT * FROM control_idempotency WHERE id = ?').get(id); }, getByKey(key) { return getDb().prepare('SELECT * FROM control_idempotency WHERE idempotency_key = ?').get(key); }, update(id, args = {}) { const current = controlIdempotency.get(id); if (!current) return null; getDb().prepare(`UPDATE control_idempotency SET status = ?, result_json = ?, updated_at = ? WHERE id = ?`).run(args.status ?? current.status, args.result !== undefined ? JSON.stringify(args.result) : current.result_json, new Date().toISOString(), id); return controlIdempotency.get(id); } };
export const repairSessions = { create(args) { const id = nanoid(14); const now = new Date().toISOString(); getDb().prepare(`INSERT INTO repair_sessions (id, task_id, initial_run_id, status, attempt_count, max_attempts, current_run_id, failure_reason, diagnosis, branch_name, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(id, args.taskId || null, args.initialRunId || null, args.status || 'open', args.attemptCount || 0, args.maxAttempts || 3, args.currentRunId || null, args.failureReason || null, args.diagnosis || null, args.branchName || null, now, now); return repairSessions.get(id); }, get(id) { return getDb().prepare('SELECT * FROM repair_sessions WHERE id = ?').get(id); }, getOpenForTask(taskId) { return getDb().prepare("SELECT * FROM repair_sessions WHERE task_id = ? AND status = 'open' ORDER BY created_at DESC LIMIT 1").get(taskId); }, getActiveForTask(taskId) { return getDb().prepare("SELECT * FROM repair_sessions WHERE task_id = ? AND status IN ('open','in_progress') ORDER BY created_at DESC LIMIT 1").get(taskId); }, update(id, fields = {}) { const current = repairSessions.get(id); if (!current) return null; const map = { status: 'status', attemptCount: 'attempt_count', currentRunId: 'current_run_id', failureReason: 'failure_reason', diagnosis: 'diagnosis', branchName: 'branch_name' }; const sets = []; const vals = []; for (const [k, v] of Object.entries(fields)) { const col = map[k]; if (!col) continue; sets.push(`${col} = ?`); vals.push(v); } if (!sets.length) return current; sets.push('updated_at = ?'); vals.push(new Date().toISOString()); vals.push(id); getDb().prepare(`UPDATE repair_sessions SET ${sets.join(', ')} WHERE id = ?`).run(...vals); return repairSessions.get(id); } };
export const notifications = { listRecent({ limit = 50 } = {}) { return getDb().prepare('SELECT * FROM notifications ORDER BY created_at DESC LIMIT ?').all(limit); }, listForRun(runId, { limit = 50 } = {}) { return getDb().prepare('SELECT * FROM notifications WHERE run_id = ? ORDER BY created_at DESC LIMIT ?').all(runId, limit); } };
