-- database/schema.sql
-- Applied idempotently on every boot via migrate() in database/index.js.

CREATE TABLE IF NOT EXISTS tasks (
  id                TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  goal              TEXT NOT NULL,
  cron_expression   TEXT,
  timezone          TEXT,
  status            TEXT NOT NULL DEFAULT 'idle',   -- idle | running | success | failed | awaiting_approval
  last_status       TEXT,
  last_run_at       TEXT,
  next_run_at       TEXT,
  error_message     TEXT,
  metadata_json     TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tasks_next_run ON tasks (next_run_at);

CREATE TABLE IF NOT EXISTS runs (
  id             TEXT PRIMARY KEY,
  task_id        TEXT NOT NULL,
  status         TEXT NOT NULL DEFAULT 'running',  -- running | success | failed | awaiting_approval
  started_at     TEXT NOT NULL,
  finished_at    TEXT,
  steps_total    INTEGER DEFAULT 0,
  steps_done     INTEGER DEFAULT 0,
  retries        INTEGER DEFAULT 0,
  result_json    TEXT,
  error_message  TEXT,
  FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_runs_task ON runs (task_id);
CREATE INDEX IF NOT EXISTS idx_runs_started ON runs (started_at);

CREATE TABLE IF NOT EXISTS steps (
  id                TEXT PRIMARY KEY,
  run_id            TEXT NOT NULL,
  seq               INTEGER NOT NULL,
  tool              TEXT NOT NULL,
  args_json         TEXT,
  reasoning         TEXT,
  status            TEXT NOT NULL DEFAULT 'pending', -- pending | running | success | failed
  observation_json  TEXT,
  error_message     TEXT,
  started_at        TEXT,
  finished_at       TEXT,
  FOREIGN KEY (run_id) REFERENCES runs (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_steps_run ON steps (run_id);

CREATE TABLE IF NOT EXISTS errors (
  id            TEXT PRIMARY KEY,
  run_id        TEXT,
  step_id       TEXT,
  level         TEXT NOT NULL,   -- debug | info | warn | error | fatal
  message       TEXT NOT NULL,
  stack         TEXT,
  context_json  TEXT,
  created_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_errors_created ON errors (created_at);

CREATE TABLE IF NOT EXISTS kv_store (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id             TEXT PRIMARY KEY,
  domain         TEXT NOT NULL,
  label          TEXT NOT NULL DEFAULT 'default',
  metadata_json  TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL,
  UNIQUE(domain, label)
);

CREATE TABLE IF NOT EXISTS notifications_log (
  id             TEXT PRIMARY KEY,
  level          TEXT NOT NULL,
  subject        TEXT NOT NULL,
  body           TEXT,
  channel        TEXT NOT NULL,
  ok             INTEGER NOT NULL DEFAULT 1,
  error_message  TEXT,
  created_at     TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications_log (created_at);

-- pending_approvals is created lazily by agent/approval.js on first use,
-- since it is only needed when HUMAN_APPROVAL_REQUIRED=true.

-- website_samples: generated by integrations/website-gen.js via the
-- generate_website tool (Phase 1 — Website Engine). Every row represents a
-- speculative sample, never a published/live site.
CREATE TABLE IF NOT EXISTS website_samples (
  id                TEXT PRIMARY KEY,   -- the sampleId returned by generateWebsite(), e.g. website_<nanoid>
  task_id           TEXT,
  run_id            TEXT,
  prospect_name     TEXT,
  status            TEXT NOT NULL DEFAULT 'SPECULATIVE_SAMPLE',
  business_type     TEXT,
  location          TEXT,
  website_goal      TEXT,
  style             TEXT,
  files_json        TEXT,
  preview_path      TEXT,
  created_at        TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_website_samples_created ON website_samples (created_at);
CREATE INDEX IF NOT EXISTS idx_website_samples_task ON website_samples (task_id);

-- prospects: real-estate businesses identified as candidates for outreach
-- (Phase 2 — Real Estate Prospecting). Populated by the save_prospect tool
-- from information the agent extracted from public pages only — never from
-- private/authenticated sources. `status` uses the Phase 8 CRM vocabulary
-- (NEW, ANALYZED, SAMPLE_CREATED, PROPOSAL_READY, AWAITING_APPROVAL,
-- CONTACTED, REPLIED, FOLLOW_UP, WON, LOST) so later phases can build on
-- this column without a migration; only 'NEW' is set by this phase.
CREATE TABLE IF NOT EXISTS prospects (
  id                TEXT PRIMARY KEY,
  task_id           TEXT,
  run_id            TEXT,
  business_name     TEXT,
  website_url       TEXT,
  location          TEXT,
  contact_email     TEXT,
  contact_phone     TEXT,
  social_profiles_json TEXT,
  service_gaps_json TEXT,
  source_url        TEXT,
  notes             TEXT,
  status            TEXT NOT NULL DEFAULT 'NEW',
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_prospects_created ON prospects (created_at);
CREATE INDEX IF NOT EXISTS idx_prospects_status ON prospects (status);
CREATE INDEX IF NOT EXISTS idx_prospects_task ON prospects (task_id);

-- opportunities: deterministic opportunity intelligence for a prospect
-- (Phase 3 — Real Estate Opportunity Intelligence). Produced by
-- integrations/opportunity-intelligence.js via the analyze_opportunity /
-- save_opportunity tools. `status` uses the same CRM vocabulary as
-- `prospects.status`; Phase 3 only ever sets NEW, ANALYZED, or
-- SAMPLE_RECOMMENDED.
CREATE TABLE IF NOT EXISTS opportunities (
  id                      TEXT PRIMARY KEY,
  prospect_id             TEXT NOT NULL,
  task_id                 TEXT,
  run_id                  TEXT,
  score                   INTEGER NOT NULL,
  priority                TEXT NOT NULL,
  opportunity_type        TEXT,
  summary                 TEXT,
  identified_problems_json    TEXT,
  recommended_services_json   TEXT,
  recommended_actions_json    TEXT,
  recommended_sample_type TEXT,
  recommended_sample_reason TEXT,
  estimated_value         TEXT,
  confidence              TEXT,
  status                  TEXT NOT NULL DEFAULT 'NEW',
  created_at              TEXT NOT NULL,
  updated_at              TEXT NOT NULL,
  FOREIGN KEY (prospect_id) REFERENCES prospects(id)
);

CREATE INDEX IF NOT EXISTS idx_opportunities_prospect ON opportunities (prospect_id);
CREATE INDEX IF NOT EXISTS idx_opportunities_status ON opportunities (status);
CREATE INDEX IF NOT EXISTS idx_opportunities_score ON opportunities (score);
CREATE INDEX IF NOT EXISTS idx_opportunities_priority ON opportunities (priority);

-- samples: a generated sample (Phase 4 — Sample & Proposal Generation) for
-- one opportunity. `status` is lifecycle ONLY (DRAFT|SAVED) — content
-- classification lives in the separate `content_kind` column
-- (SPECULATIVE_SAMPLE|CONCEPT_BRIEF), never mixed into `status`. For
-- sample_type='website', website_sample_id must reference the exact
-- website_samples row created by the same create_sample/generate_website
-- call — ownership is enforced at the application layer in
-- database/index.js (samples.create), not just by this FK.
CREATE TABLE IF NOT EXISTS samples (
  id                TEXT PRIMARY KEY,
  prospect_id       TEXT NOT NULL,
  opportunity_id    TEXT NOT NULL,
  task_id           TEXT,
  run_id            TEXT,
  sample_type       TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'DRAFT',   -- DRAFT | SAVED (lifecycle only)
  content_kind      TEXT NOT NULL,                   -- SPECULATIVE_SAMPLE | CONCEPT_BRIEF (content classification only)
  website_sample_id TEXT,
  concept_content_json TEXT,
  preview_path      TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  FOREIGN KEY (prospect_id) REFERENCES prospects(id),
  FOREIGN KEY (opportunity_id) REFERENCES opportunities(id),
  FOREIGN KEY (website_sample_id) REFERENCES website_samples(id)
);

CREATE INDEX IF NOT EXISTS idx_samples_opportunity ON samples (opportunity_id);
CREATE INDEX IF NOT EXISTS idx_samples_prospect ON samples (prospect_id);
CREATE INDEX IF NOT EXISTS idx_samples_status ON samples (status);
CREATE INDEX IF NOT EXISTS idx_samples_content_kind ON samples (content_kind);

-- proposals: a drafted proposal (Phase 4) for one opportunity + sample.
-- `status` DRAFT|READY. Reaching READY (via save_proposal) is what moves
-- the parent opportunity to AWAITING_APPROVAL — see database/index.js.
CREATE TABLE IF NOT EXISTS proposals (
  id                      TEXT PRIMARY KEY,
  prospect_id             TEXT NOT NULL,
  opportunity_id          TEXT NOT NULL,
  sample_id               TEXT,
  task_id                 TEXT,
  run_id                  TEXT,
  status                  TEXT NOT NULL DEFAULT 'DRAFT',   -- DRAFT | READY
  pitch                   TEXT,
  service_recommendation  TEXT,
  value_proposition       TEXT,
  suggested_package       TEXT,
  call_to_action          TEXT,
  assumptions_json        TEXT,
  created_at              TEXT NOT NULL,
  updated_at              TEXT NOT NULL,
  FOREIGN KEY (prospect_id) REFERENCES prospects(id),
  FOREIGN KEY (opportunity_id) REFERENCES opportunities(id),
  FOREIGN KEY (sample_id) REFERENCES samples(id)
);

CREATE INDEX IF NOT EXISTS idx_proposals_opportunity ON proposals (opportunity_id);
CREATE INDEX IF NOT EXISTS idx_proposals_prospect ON proposals (prospect_id);
CREATE INDEX IF NOT EXISTS idx_proposals_status ON proposals (status);
