import { spawn } from 'node:child_process';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
const clean=v=>String(v??'').trim();
const safe=(v,f='creative')=>clean(v).replace(/[^a-z0-9_-]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,80)||f;
const palettes={luxury:['#f7f2ea','#171717','#b89b5e'],fashion:['#f5f0eb','#161616','#d6bfa8'],corporate:['#f5f7fa','#0f172a','#2563eb'],church:['#eef5ff','#16325c','#c8a75b'],default:['#f5f5f5','#171717','#9b7b4f']};
export const FREE_RENDER_VERSION='1.0.0';
export const FREE_RENDER_MODES=Object.freeze(['browser-compositor','ffmpeg','comfyui','blender']);
export function resolveLocalRenderConfig(env=process.env){return Object.freeze({outputDir:clean(env.CREATIVE_OUTPUT_DIR||env.DATA_DIR||'/data')||'/data',comfyuiBaseUrl:clean(env.COMFYUI_BASE_URL),ffmpegBin:clean(env.FFMPEG_BIN)||'ffmpeg',defaultFps:Number(env.CREATIVE_FPS||24)});}
export function localCreativeCapabilities(env=process.env){const c=resolveLocalRenderConfig(env);return {version:FREE_RENDER_VERSION,freeLocal:{enabled:true,mode:'browser-compositor',image:true,video:true},selfHosted:{comfyui:!!c.comfyuiBaseUrl,blender:!!clean(env.BLENDER_BIN),image:true,video:true,threeD:!!clean(env.BLENDER_BIN)},optionalPaid:{runway:!!clean(env.RUNWAY_API_KEY),meshy:!!clean(env.MESHY_API_KEY),shotstack:!!clean(env.SHOTSTACK_API_KEY)}};}
function esc(v){return clean(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function html(o){const p=o.palette,bg=p[0],fg=p[1],accent=p[2],vertical=o.ratio==='9:16';const title=esc(o.title),subtitle=esc(o.subtitle),eyebrow=esc(o.eyebrow);return '<!doctype html><html><head><meta charset="utf-8"><style>*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden}body{background:radial-gradient(circle at 78% 18%,'+accent+'30 0,transparent 34%),linear-gradient(135deg,'+bg+','+bg+');font-family:Inter,Arial,sans-serif;color:'+fg+'}.frame{position:relative;width:100vw;height:100vh;padding:'+(vertical?'8vh 8vw':'7vh 7vw')+';display:flex;flex-direction:column;justify-content:center}.orb{position:absolute;width:42vw;height:42vw;border-radius:50%;right:-13vw;top:-12vw;background:'+accent+';opacity:.12}.eyebrow{font-size:'+(vertical?'2.1vw':'1.25vw')+';letter-spacing:.24em;text-transform:uppercase;color:'+accent+';font-weight:700;margin-bottom:2.4vh}.title{font-size:'+(vertical?'8vw':'6vw')+';line-height:.94;max-width:'+(vertical?'86vw':'70vw')+';font-weight:800;letter-spacing:-.045em}.subtitle{font-size:'+(vertical?'2.7vw':'1.8vw')+';line-height:1.35;max-width:'+(vertical?'78vw':'56vw')+';margin-top:3vh;opacity:.78}.rule{width:12vw;height:4px;background:'+accent+';margin-top:4vh}.meta{position:absolute;bottom:5vh;left:7vw;right:7vw;display:flex;justify-content:space-between;font-size:1vw;letter-spacing:.12em;text-transform:uppercase;opacity:.55}.progress{position:absolute;left:7vw;bottom:3vh;height:3px;width:86vw;background:'+fg+'18}.progress i{display:block;height:100%;width:'+o.progress+'%;background:'+accent+'}</style></head><body><main class="frame"><div class="orb"></div><div class="eyebrow">'+eyebrow+'</div><div class="title">'+title+'</div><div class="subtitle">'+subtitle+'</div><div class="rule"></div><div class="meta"><span>Creative Engine</span><span>'+o.scene+'/'+o.total+'</span></div><div class="progress"><i></i></div></main></body></html>';}
function exec(cmd,args){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{stdio:['ignore','pipe','pipe']});let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',c=>c===0?resolve({out,err}):reject(Object.assign(new Error(cmd+' failed: '+c),{out,err})))});}
function pick(project){const i=clean(project?.intelligence?.industry||project?.brief?.industry).toLowerCase();const k=Object.keys(palettes).find(x=>i.includes(x));return palettes[k||'default'];}
export async function renderLocalImage({project={},outputDir=resolveLocalRenderConfig().outputDir,filename}={}){const dir=path.resolve(outputDir);await mkdir(dir,{recursive:true});const spec=project.spec||project.brief||{};const file=path.join(dir,filename||safe(project.name||project.type)+'-image.png');const b=await import('playwright');const browser=await b.chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:Number(spec.width||1920),height:Number(spec.height||1080)}});await page.setContent(html({title:spec.title||project.brief?.name||'Professional Creative',subtitle:spec.description||project.brief?.description||'Premium visual communication',eyebrow:spec.industry||project.brief?.industry||'Creative Studio',ratio:spec.ratio||'16:9',palette:pick(project),progress:100,scene:1,total:1}),{waitUntil:'load'});await page.screenshot({path:file,type:'png'});}finally{await browser.close()}return {provider:'free-local-browser',mode:'browser-compositor',format:'png',path:file};}
export async function renderLocalVideo({project={},outputDir=resolveLocalRenderConfig().outputDir,filename,fps=24,scenes=6}={}){const dir=path.resolve(outputDir);const work=path.join(dir,'creative-'+Date.now()+'-'+safe(project.name||project.type));await mkdir(work,{recursive:true});const spec=project.spec||project.brief||{};const ratio=spec.ratio||'16:9',vertical=ratio==='9:16',width=vertical?1080:1920,height=vertical?1920:1080;const b=await import('playwright');const browser=await b.chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width,height}});const copy=['Build desire.','Make it memorable.','Turn attention into action.','Designed for your brand.','Built for every screen.'];for(let i=0;i<scenes;i++){await page.setContent(html({title:i===0?(spec.title||project.brief?.name||'Premium Creative'):(copy[i-1]||'Made to perform.'),subtitle:spec.description||project.brief?.description||'Professional visual storytelling.',eyebrow:spec.industry||project.brief?.industry||'Creative Studio',ratio,palette:pick(project),progress:((i+1)/scenes)*100,scene:i+1,total:scenes}),{waitUntil:'load'});await page.screenshot({path:path.join(work,'frame-'+String(i+1).padStart(4,'0')+'.png'),type:'png'})}}finally{await browser.close()}const file=path.join(dir,filename||safe(project.name||project.type)+'-video.mp4');await exec(resolveLocalRenderConfig().ffmpegBin,['-y','-framerate',String(fps),'-i',path.join(work,'frame-%04d.png'),'-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart',file]);return {provider:'free-local-browser+ffmpeg',mode:'browser-compositor',format:'mp4',path:file,scenes,fps};}
export async function renderComfyUI({prompt,workflow,baseUrl=resolveLocalRenderConfig().comfyuiBaseUrl}={}){if(!baseUrl)throw new Error('COMFYUI_BASE_URL is required for self-hosted AI rendering');if(!prompt&&!workflow)throw new Error('prompt or workflow is required');const r=await fetch(baseUrl.replace(/\/$/,'')+'/prompt',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(workflow||{prompt})});if(!r.ok)throw new Error('ComfyUI queue failed: '+r.status);return {provider:'self-hosted-comfyui',mode:'comfyui',queued:true};}
export async function renderFreeFirst({project={},options={}}={}){const type=String(project.type||'graphic').toLowerCase();if(type==='video')return renderLocalVideo({project,outputDir:options.outputDir,filename:options.filename,fps:options.fps||24,scenes:options.scenes||6});if(type==='graphic'||type==='image')return renderLocalImage({project,outputDir:options.outputDir,filename:options.filename});if(type==='3d'||type==='three-d')throw new Error('Free 3D requires a Blender scene or self-hosted Blender worker');throw new Error('Unsupported free render type: '+type);}