const clean = value => String(value ?? '').trim();
const ALLOWED_FIELDS = Object.freeze(['description','industry','audience','goal','platform','duration','format','genre','type','theme','tone','cta','copy','colors','typography','layout','composition','motion','music','voiceover','captionStyle','safeArea','lighting','camera','materials','renderMode']);
const STAGES = Object.freeze(['CLIENT_REVIEW','REVISION_REQUESTED','REGENERATING','QA','APPROVED']);
export const CREATIVE_REVISION_VERSION = '1.0.0';
export const REVISION_LIMITS = Object.freeze({maxRequests:10,maxChangesPerRequest:12,maxHistory:50});
export function createRevisionSession(project={}, options={}) { const id=clean(options.sessionId||project.id||project.name||'creative-project').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'') || 'creative-project'; return {version:CREATIVE_REVISION_VERSION,sessionId:id,stage:'CLIENT_REVIEW',revisionCount:0,maxRequests:options.maxRequests||REVISION_LIMITS.maxRequests,history:[],currentSnapshot:options.snapshot||project.spec||null,approved:false}; }
export function normalizeRevisionRequest(input={}) { const raw=typeof input==='string'?{request:input}:input; const changes=Array.isArray(raw.changes)?raw.changes:[]; const safeChanges=changes.slice(0,REVISION_LIMITS.maxChangesPerRequest).map(change=>({field:clean(change.field),value:change.value,reason:clean(change.reason)})).filter(change=>ALLOWED_FIELDS.includes(change.field)); return {request:clean(raw.request||raw.description),changes:safeChanges,requestedBy:clean(raw.requestedBy||raw.client||'client'),priority:clean(raw.priority||'normal')||'normal'}; }
export function applyTargetedRevision(snapshot={}, request={}) { const normalized=normalizeRevisionRequest(request); const next={...snapshot}; for(const change of normalized.changes) next[change.field]=change.value; return {snapshot:next,applied:normalized.changes.map(change=>change.field),rejected:Math.max(0,(Array.isArray(request.changes)?request.changes.length:0)-normalized.changes.length),request:normalized}; }
export function requestCreativeRevision(session={}, request={}) { if(!session||!session.sessionId) throw new Error('revision session is required'); if(session.approved) return {ok:false,code:'ALREADY_APPROVED',session}; if(session.revisionCount >= (session.maxRequests||REVISION_LIMITS.maxRequests)) return {ok:false,code:'REVISION_LIMIT_REACHED',session}; const normalized=normalizeRevisionRequest(request); if(!normalized.request&&!normalized.changes.length) return {ok:false,code:'EMPTY_REVISION_REQUEST',session}; const next={...session,stage:'REVISION_REQUESTED',revisionCount:session.revisionCount+1,history:[...(session.history||[]),{stage:'REVISION_REQUESTED',revision:session.revisionCount+1,request:normalized}].slice(-REVISION_LIMITS.maxHistory)}; return {ok:true,session:next,request:normalized}; }
export function applyRevisionAndQueueQA(session={}, request={}) { const result=requestCreativeRevision(session,request); if(!result.ok) return result; const applied=applyTargetedRevision(session.currentSnapshot||{},request); return {ok:true,session:{...result.session,stage:'QA',currentSnapshot:applied.snapshot,history:[...result.session.history,{stage:'REGENERATING',revision:result.session.revisionCount,applied:applied.applied,rejected:applied.rejected}].slice(-REVISION_LIMITS.maxHistory)},applied,rejected:applied.rejected}; }
export function approveCreativeRevision(session={}) { if(!session.sessionId) return {ok:false,code:'REVISION_SESSION_REQUIRED'}; if(session.stage!=='QA'&&session.stage!=='CLIENT_REVIEW') return {ok:false,code:'QA_REQUIRED'}; return {ok:true,session:{...session,stage:'APPROVED',approved:true,history:[...(session.history||[]),{stage:'APPROVED',revision:session.revisionCount}].slice(-REVISION_LIMITS.maxHistory)}}; }
export function validateRevisionSession(session={}) { const failures=[]; if(!session.sessionId) failures.push('missing-session-id'); if(!STAGES.includes(session.stage)) failures.push('invalid-stage'); if(!Number.isInteger(session.revisionCount)||session.revisionCount<0) failures.push('invalid-revision-count'); if(session.revisionCount>(session.maxRequests||REVISION_LIMITS.maxRequests)) failures.push('revision-limit-exceeded'); if(!Array.isArray(session.history)) failures.push('missing-history'); return {passed:failures.length===0,failures}; }
