export const VISUAL_QA_VERSION='1.0.0';
export const VIEWPORTS=Object.freeze({mobile:{width:390,height:844},tablet:{width:768,height:1024},laptop:{width:1366,height:768},desktop:{width:1440,height:900},largeDesktop:{width:1920,height:1080}});
export const VISUAL_QA_CHECKS=Object.freeze(['layout','overflow','contrast','hierarchy','media','responsive','motion','threeD']);
const arr=v=>Array.isArray(v)?v:[];
export function normalizeVisualEvidence(input={}){return {viewport:String(input.viewport||'desktop'),overflow:input.overflow===true,contrast:input.contrast!==false,layout:input.layout!==false,hierarchy:input.hierarchy!==false,media:input.media!==false,responsive:input.responsive!==false,motion:input.motion!==false,threeD:input.threeD!==false,issues:arr(input.issues).map(String)};}
export function runVisualQA(evidence={}){const e=normalizeVisualEvidence(evidence),failures=[];if(e.overflow)failures.push('layout overflow detected');for(const key of ['layout','contrast','hierarchy','media','responsive','motion','threeD'])if(e[key]===false)failures.push(key+' check failed');return {passed:failures.length===0,version:VISUAL_QA_VERSION,viewport:e.viewport,checks:VISUAL_QA_CHECKS,failures,issues:e.issues};}
export function createVisualQAMatrix(evidenceByViewport={}){return Object.entries(VIEWPORTS).map(([name,viewport])=>{const result=runVisualQA({...evidenceByViewport[name],viewport:name});return {viewport:name,dimensions:viewport,...result};});}
export function buildVisualQAReport(project={},evidenceByViewport={}){const matrix=createVisualQAMatrix(evidenceByViewport),failures=matrix.flatMap(x=>x.failures.map(f=>x.viewport+': '+f));return {engine:'professional-creative-visual-qa',version:VISUAL_QA_VERSION,project:String(project.name||project.id||'creative-project'),passed:failures.length===0,viewports:matrix,failures,repairRequired:failures.length>0};}
export function queueVisualRepair(report={}){if(report.passed)return {queued:false,reason:'visual QA passed'};return {queued:true,maxAttempts:3,issues:[...arr(report.failures)],status:'REPAIR_REQUIRED'};}
