import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
let dbPath, closeDb, migrate, tasks, prospects, opportunities, conversations;
beforeAll(async()=>{dbPath=path.join(os.tmpdir(),`business-growth-${Date.now()}.db`);process.env.DATABASE_PATH=dbPath;process.env.DATA_DIR=path.dirname(dbPath);process.env.AI_PROVIDER='stub';({closeDb,migrate,tasks,prospects,opportunities,conversations}=await import('../../database/index.js'));closeDb();migrate();});
afterAll(()=>{try{closeDb();}catch{}try{fs.unlinkSync(dbPath);}catch{}});
describe('business growth engine',()=>{
 it('creates a bounded revenue hunter task',async()=>{const {createRevenueHunter}=await import('../../integrations/business-growth.js');const r=createRevenueHunter({targetMarket:'luxury hotels',idealCustomer:'independent hotels',offer:'premium website transformation',geography:'Dubai',maxProspects:25});expect(r.ok).toBe(true);expect(r.task.metadata_json).toContain('AI_REVENUE_HUNTER');expect(r.goal).toContain('Do not send unsolicited outreach');});
 it('creates an autopilot task with bounded autonomy',async()=>{const {buildAutopilot,AUTOPILOT_MODES}=await import('../../integrations/business-growth.js');const r=buildAutopilot({goal:'increase qualified leads',mode:AUTOPILOT_MODES.AUTOPILOT,successMetrics:['10 qualified leads'],allowedActions:['research','draft'],approvalThresholds:{externalSend:'approval_required'}});expect(r.ok).toBe(true);expect(r.mode).toBe('AUTOPILOT');expect(r.task.goal).toContain('Never bypass existing approval');});
 it('persists opportunity radar results',async()=>{const {runOpportunityRadar}=await import('../../integrations/business-growth.js');const p=prospects.create({businessName:'Radar Realty',websiteUrl:null,contactEmail:null,contactPhone:null,socialProfiles:[],serviceGaps:[],status:'NEW'});const r=runOpportunityRadar({limit:10,minScore:1});const match=r.opportunities.find(x=>x.prospect.id===p.id);expect(match).toBeTruthy();expect(match.opportunity.score).toBeGreaterThan(0);expect(opportunities.getOpportunitiesForProspect(p.id,{limit:1})).toHaveLength(1);});
 it('finds stale conversations without sending',async()=>{const {getFollowUps}=await import('../../integrations/business-growth.js');const c=conversations.create({channel:'whatsapp',externalThreadId:`test-${Date.now()}`,status:'OPEN',summary:'Interested in a website quote'});const {getDb}=await import('../../database/index.js');getDb().prepare('UPDATE conversations SET last_message_at = ? WHERE id = ?').run(new Date(Date.now()-7*86400000).toISOString(),c.id);const r=await getFollowUps({minDays:3,includeDrafts:false});expect(r.followUps.some(x=>x.conversation.id===c.id)).toBe(true);expect(r.externalSideEffect).toBe(false);});
 it('builds a full marketing campaign blueprint',async()=>{const {buildMarketingCampaign}=await import('../../integrations/business-growth.js');const r=buildMarketingCampaign({brief:'Launch a premium hotel offer',objective:'generate qualified bookings',audience:'international travelers',offer:'premium weekend package',channels:['website','whatsapp','email','social','video','crm']});expect(r.ok).toBe(true);expect(r.stages).toHaveLength(5);expect(r.automation.opportunityRadar).toBe(true);expect(r.approvals).toContain('external outreach/send');});
 it('creates a durable campaign task',async()=>{const {createCampaignTask}=await import('../../integrations/business-growth.js');const r=createCampaignTask({brief:'Launch a restaurant menu campaign',objective:'generate qualified leads',channels:['website','whatsapp','crm'],cronExpression:'0 9 * * 1',timezone:'Africa/Dar_es_Salaam'});expect(r.ok).toBe(true);expect(r.task.cron_expression).toBe('0 9 * * 1');expect(tasks.get(r.task.id)).toBeTruthy();});
});
