import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
let dbPath,closeDb,migrate;
beforeAll(async()=>{dbPath=path.join(os.tmpdir(),'deep-crm-loop-'+Date.now()+'.db');process.env.DATABASE_PATH=dbPath;process.env.DATA_DIR=path.dirname(dbPath);process.env.AI_PROVIDER='stub';({closeDb,migrate}=await import('../../database/index.js'));closeDb();migrate();});
afterAll(()=>{try{closeDb();}catch{}try{fs.unlinkSync(dbPath);}catch{}});
describe('deep CRM ecosystem',()=>{
 it('registers provider-neutral integrations',async()=>{const m=await import('../../integrations/deep-business-autopilot.js');const r=m.registerDeepCRMIntegration({system:'crm',provider:'generic-crm',capabilities:['contacts.read','contacts.write','deals.read','deals.write']});expect(r.system).toBe('crm');expect(m.listDeepCRMIntegrations().some(x=>x.provider==='generic-crm')).toBe(true);});
 it('supports CRM ecosystem system classes',async()=>{const m=await import('../../integrations/deep-business-autopilot.js');for(const system of m.DEEP_CRM_SYSTEMS)m.registerDeepCRMIntegration({system,provider:'generic-'+system});expect(m.DEEP_CRM_SYSTEMS).toEqual(['crm','accounting','sales_engagement','calendar','payments','support']);});
 it('creates a durable 30-day loop',async()=>{const m=await import('../../integrations/deep-business-autopilot.js');const r=m.createAutonomousBusinessLoop({name:'Lead Growth',goal:'Generate qualified leads and improve conversion',durationDays:30,cadence:'0 9 * * *',successMetrics:['qualified leads','conversion rate'],allowedActions:['research','qualify','prepare_follow_up']});expect(r.status).toBe('ACTIVE');expect(r.ends_at).toBeTruthy();expect(r.task_id).toBeTruthy();});
 it('records checkpoint state and adapts strategy',async()=>{const m=await import('../../integrations/deep-business-autopilot.js');const r=m.createAutonomousBusinessLoop({name:'Adaptive Loop',goal:'Improve follow-up conversion',durationDays:30});const c=m.checkpointAutonomousLoop({loopId:r.id,outcome:{signal:'negative',evidence:'response rate dropped'},exceptions:['approval_required']});expect(c.ok).toBe(true);expect(c.checkpoint.strategyAfter.priority).toBe('exception_first');expect(m.getAutonomousLoopCheckpoints(r.id)).toHaveLength(1);});
 it('builds customer 360 without external side effects',async()=>{const m=await import('../../integrations/deep-business-autopilot.js');const {companies}=await import('../../database/index.js');const c=companies.create({name:'360 Test Company'});const r=m.getCustomer360({companyId:c.id});expect(r.company.id).toBe(c.id);expect(r.externalSideEffect).toBe(false);expect(Array.isArray(r.memory)).toBe(true);});
});
