import { describe, expect, it } from 'vitest';
import { buildWebsite } from '../../website-engine/index.js';
import { createRevisionPatch, createResponsiveSystem, createVisualRuntimeManifest, createInformationArchitecture, createCrmManifest, selfCritiqueWebsite, buildRepairPlan, certifyWebsite, buildCommercialManifest, VIEWPORT_MATRIX } from '../../website-engine/advanced.js';

describe('Website Engine end-to-end commercial phases C-L',()=>{
 it('C responsive system is explicit and complete',()=>{const s=buildWebsite({industry:'fashion',description:'luxury fashion brand'});expect(s.responsive.breakpoints.md).toBe(768);expect(s.responsive.touchTarget).toBe(44);expect(s.qa.responsive.passed).toBe(true);expect(VIEWPORT_MATRIX.length).toBeGreaterThanOrEqual(5);});
 it('D visual runtime has progressive capability and fallback contracts',()=>{const s=buildWebsite({description:'interactive 3D automotive experience',use3D:true});expect(s.visualRuntime.threeD.enabled).toBe(true);expect(s.visualRuntime.threeD.fallback).toBeTruthy();expect(s.qa.visualRuntime.passed).toBe(true);expect(s.files['app.js']).toContain('canWebGL');});
 it('E visual QA remains green',()=>{const s=buildWebsite({industry:'hotel',description:'premium resort experience'});expect(s.qa.visual.passed).toBe(true);});
 it('F information architecture and structured content are generated',()=>{const s=buildWebsite({industry:'education',description:'modern learning platform',desiredPages:['home','courses','about','contact']});expect(s.informationArchitecture.primaryNavigation).toHaveLength(4);expect(s.informationArchitecture.contentModel.separateContentFromComponents).toBe(true);expect(s.qa.content.passed).toBe(true);});
 it('G CRM lead contract is explicit',()=>{const s=buildWebsite({industry:'restaurant',description:'fine dining restaurant'});expect(s.crm.endpoint).toBe('/api/website/leads');expect(s.crm.fields.find(x=>x.name==='consent').required).toBe(true);expect(s.files['index.html']).toContain('data-crm-form');});
 it('H SEO accessibility performance gates are green',()=>{const s=buildWebsite({industry:'architecture',description:'architecture studio'});expect(s.qa.seoAccessibilityPerformance.passed).toBe(true);expect(s.files['sitemap.xml']).toContain('<urlset');expect(s.files['robots.txt']).toContain('Sitemap: /sitemap.xml');});
 it('I revision patches are deterministic and scoped',()=>{const p=createRevisionPatch({type:'style',target:'hero',instruction:'Increase visual contrast',value:'high'});expect(p.deterministic).toBe(true);expect(p.type).toBe('style');expect(p.target).toBe('hero');});
 it('J deployment remains approval-gated through certification',()=>{const s=buildWebsite({industry:'saas',description:'enterprise AI SaaS'});expect(certifyWebsite(s,{state:'DRAFT'}).certified).toBe(true);});
 it('K self-critique produces a clean repair plan',()=>{const s=buildWebsite({});const c=selfCritiqueWebsite(s);expect(c.passed).toBe(true);expect(buildRepairPlan(c).repairCount).toBe(0);});
 it('L commercial certification and delivery manifest are production-shaped',()=>{const s=buildWebsite({industry:'luxury',description:'premium brand experience'});const c=certifyWebsite(s,{state:'APPROVED'});const m=buildCommercialManifest(s,{projectId:'wp_test',state:'APPROVED',versions:[{version:1}]});expect(c.status).toBe('CERTIFIED');expect(m.certification.certified).toBe(true);expect(m.deployment).toBe('approval-gated');expect(m.certification.secretsIncluded).toBe(false);});
 it('advanced contracts compose independently',()=>{const s=buildWebsite({industry:'automotive',description:'interactive product website'});expect(createResponsiveSystem(s.spec).layout.mobile).toBe('single-column');expect(createVisualRuntimeManifest(s.spec,s.media).renderer).toBe('progressive-webgl');expect(createInformationArchitecture({},s.spec,s.content).primaryNavigation.length).toBeGreaterThan(0);expect(createCrmManifest({},s.spec).endpoint).toBe('/api/website/leads');});
});
