// Objective-driven orchestration: compose existing intelligence into a bounded execution graph.
// Existing production modules are reused; this layer never sends, charges, deploys, or bypasses approval.
import { nanoid } from 'nanoid';
import { qualifyClient, buildWhatsAppPresentation, revenueIntelligence } from '../integrations/client-revenue-intelligence.js';
import { getCustomer360, getFollowUps, runOpportunityRadar } from '../integrations/business-growth.js';
import { generateBusinessAnalystBrief } from '../integrations/client-intelligence.js';
import { generateWebsite } from '../integrations/website-gen.js';
import { createCreativeProject, validateCreativeProject } from '../creative-engine/index.js';
import { CAPABILITIES, selectCapabilities } from './capabilities.js';
const clean=v=>String(v??'').trim(), lower=v=>clean(v).toLowerCase(), any=(s,w)=>w.some(x=>s.includes(x));
const defs={
 'client.intelligence':{capability:'client_intelligence',run:qualifyClient},
 'client.whatsapp_presentation':{capability:'presentation',run:buildWhatsAppPresentation},
 'revenue.intelligence':{capability:'revenue_intelligence',run:revenueIntelligence},
 'crm.customer_360':{capability:'customer_360',run:getCustomer360},
 'growth.opportunity_radar':{capability:'opportunity_radar',run:runOpportunityRadar},
 'growth.follow_ups':{capability:'follow_up',run:getFollowUps},
 'bi.analyst_brief':{capability:'business_analysis',run:generateBusinessAnalystBrief},
};
export function classifyObjective(objective=''){const g=lower(objective);if(any(g,['revenue','sales','sell','close','grow income','increase income']))return 'REVENUE_GROWTH';if(any(g,['lead','prospect','qualif','client','customer','proposal','present']))return 'CLIENT_REVENUE';if(any(g,['website','landing page','web site']))return 'WEBSITE_DELIVERY';if(any(g,['creative','design','video','3d','brand']))return 'CREATIVE_DELIVERY';if(any(g,['analy','report','business health','performance','funnel']))return 'BUSINESS_ANALYSIS';return 'GENERAL_BUSINESS';}
function makeStep(tool,args,dependsOn=[],reason=''){return {id:'step_'+nanoid(8),tool,args,dependsOn,capability:defs[tool]?.capability||tool,reason};}
export function planObjective({objective,prospectId,businessName,maxSteps=8}={}){const goal=clean(objective);if(!goal)throw new Error('objective is required');const type=classifyObjective(goal),steps=[],clientArgs=prospectId?{prospectId}:businessName?{businessName}:{};
 if(type==='CLIENT_REVENUE'){if(Object.keys(clientArgs).length){steps.push(makeStep('client.intelligence',clientArgs,[],'Establish client context, qualification, memory and next action.'));steps.push(makeStep('client.whatsapp_presentation',{...clientArgs,maxSamples:3},[steps[0].id],'Use client intelligence to prepare a matched presentation without sending it.'));}else steps.push(makeStep('revenue.intelligence',{days:30},[],'Measure commercial context before selecting a client action.'));steps.push(makeStep('revenue.intelligence',{days:30},[steps[steps.length-1].id],'Close the loop with current funnel and revenue evidence.'));}
 else if(type==='REVENUE_GROWTH'){steps.push(makeStep('revenue.intelligence',{days:30},[],'Measure the funnel first.'));steps.push(makeStep('growth.opportunity_radar',{limit:50},[steps[0].id],'Identify high-value opportunities from current prospect evidence.'));steps.push(makeStep('growth.follow_ups',{limit:50,minDays:3,includeDrafts:true},[steps[1].id],'Prioritize follow-up work after opportunity discovery.'));}
 else if(type==='BUSINESS_ANALYSIS'){steps.push(makeStep('revenue.intelligence',{days:30},[],'Measure revenue and funnel signals.'));if(Object.keys(clientArgs).length)steps.push(makeStep('bi.analyst_brief',clientArgs,[steps[0].id],'Turn existing BI/client signals into an executive brief.'));}
 else {if(Object.keys(clientArgs).length)steps.push(makeStep('client.intelligence',clientArgs,[],'Ground the objective in client intelligence.'));steps.push(makeStep('supervisor.capabilities',{goal,requestedService:goal},steps.length?[steps[0].id]:[],'Discover existing capabilities before acting.'));steps.push(makeStep('revenue.intelligence',{days:30},[steps[steps.length-1].id],'Align priority with commercial evidence.'));}
 const limited=steps.slice(0,Math.max(1,Math.min(Number(maxSteps)||8,12)));return {ok:true,planner:'OBJECTIVE_DRIVEN_ORCHESTRATOR',version:1,planId:'plan_'+nanoid(10),objective:goal,objectiveType:type,steps:limited,capabilityComposition:[...new Set(limited.map(s=>s.capability))],executionPolicy:{bounded:true,denyByDefault:true,externalSendForbidden:true,approvalBoundariesPreserved:true},selection:{existingCapabilities:selectCapabilities({goal,requestedService:goal}),reason:'Choose only registered production modules and order them by information dependencies.'}};}
export function validateObjectivePlan(plan){if(!plan?.steps?.length)return {ok:false,reason:'empty plan'};const ids=new Set(plan.steps.map(s=>s.id));for(const s of plan.steps){if(s.tool!=='supervisor.capabilities'&&!defs[s.tool])return {ok:false,reason:'unsupported objective tool: '+s.tool};if((s.dependsOn||[]).some(id=>!ids.has(id)))return {ok:false,reason:'invalid dependency: '+s.id};}return {ok:true,stepCount:plan.steps.length};}
export async function runObjective(input={},options={}){const plan=input.plan||planObjective({objective:input.objective||input.goal||input.body,prospectId:input.prospectId,businessName:input.businessName,maxSteps:input.maxSteps});const validation=validateObjectivePlan(plan);if(!validation.ok)throw new Error(validation.reason);const results=[],outputs=new Map();for(const s of plan.steps){if((s.dependsOn||[]).some(id=>!results.find(r=>r.stepId===id&&r.status==='success'))){results.push({stepId:s.id,tool:s.tool,status:'blocked',reason:'dependency did not complete'});continue;}if(s.tool==='supervisor.capabilities'){const result={ok:true,capabilities:Object.values(CAPABILITIES),selected:selectCapabilities({goal:plan.objective,requestedService:plan.objective})};outputs.set(s.id,result);results.push({stepId:s.id,tool:s.tool,status:'success',result,externalSideEffect:false});continue;}const def=defs[s.tool];try{const args={...(s.args||{})};const prior=[...outputs.values()].find(v=>v?.client?.id);if(!args.prospectId&&prior?.client?.id&&s.tool==='client.whatsapp_presentation')args.prospectId=prior.client.id;const result=await def.run(args);outputs.set(s.id,result);results.push({stepId:s.id,tool:s.tool,status:'success',result,externalSideEffect:result?.externalSideEffect===true});}catch(error){results.push({stepId:s.id,tool:s.tool,status:'failed',error:error.message});break;}}const failed=results.filter(r=>r.status==='failed'),blocked=results.filter(r=>r.status==='blocked'),successful=results.filter(r=>r.status==='success');return {ok:failed.length===0&&successful.length>0,journeyId:'objective_'+nanoid(12),objective:plan.objective,objectiveType:plan.objectiveType,plan,validation,status:blocked.length?'AWAITING_APPROVAL':failed.length?'FAILED':'COMPLETED',results,completedSteps:successful.length,blockedSteps:blocked.length,failedSteps:failed.length,externalSideEffect:results.some(r=>r.externalSideEffect===true),requiresHumanApproval:false,nextAction:blocked.length?'Resolve the blocked dependency or capability selection.':'Objective checkpoint completed; use the result to choose the next objective.'};}
export { defs as OBJECTIVE_STEP_DEFS };
